/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (unauthenticated) */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Echo the caller's verified identity */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller org's sites */
        get: operations["listSites"];
        put?: never;
        /**
         * Create a site
         * @description Reserved slugs are rejected (400). On the cloud build, exceeding the per-user site cap returns 402 with the quota body so the dashboard can open the upgrade modal.
         */
        post: operations["createSite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one site */
        get: operations["getSite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sites/{id}/deployments/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prepare a deployment — discover missing blobs + presigned uploads
         * @description Given the deploy manifest, returns the subset of referenced blobs not already present for the org (only-changed-blob upload) and a presigned PUT URL for each. Blob keys are derived server-side from the org + sha256.
         */
        post: operations["prepareDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sites/{id}/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize a deployment — verify blobs, write the immutable version
         * @description Server-verifies that every referenced blob is present AND its stored bytes hash equals the claimed sha256, writes the immutable per-deploy manifest to object storage, and inserts an immutable site_version (status=ready, next version_no). Idempotent on the per-site content digest.
         */
        post: operations["finalizeDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sites/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish (or roll back to) a version
         * @description Flips the site's live-version pointer to version_id and writes the edge routing projection (KV route:<host>). Rollback is just publishing an older version_id. The pointer flip is Postgres-authoritative; the projection is a rebuildable cache.
         */
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            user_id?: string;
            org_id?: string;
            /** @enum {string} */
            role?: "owner" | "admin" | "member";
        };
        Site: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            org_id?: string;
            slug?: string;
            /** Format: uuid */
            owner_id?: string;
            /** @enum {string} */
            access_mode?: "public" | "password" | "allowlist" | "org_only";
            /** Format: uuid */
            current_version_id?: string | null;
            /** Format: uri */
            live_url?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Version: {
            /** Format: uuid */
            version_id?: string;
            version_no?: number;
            /** Format: uri */
            preview_url?: string;
        };
        ManifestFile: {
            /** @description Request path served from the site (e.g. index.html, assets/app.js). */
            path: string;
            /** @description Content hash (lowercase hex). The server derives the R2 key from org + this. */
            sha256: string;
            /** Format: int64 */
            size: number;
            content_type?: string;
        };
        Error: {
            /** @description Stable machine-readable code */
            error?: string;
            message?: string;
        };
        /** @description 402 body (see internal/quota.ExceededError); the dashboard opens the upgrade/sales modal. */
        QuotaExceeded: {
            /** @enum {string} */
            limit?: "sites_per_user" | "members_per_org";
            /** Format: int64 */
            current?: number;
            /** Format: int64 */
            max?: number;
            plan_tier?: string;
            next_tier?: string;
            /** Format: uri */
            upgrade_url?: string;
            /** Format: uri */
            sales_url?: string;
        };
    };
    responses: {
        /** @description Missing/invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Malformed request / reserved slug / verification failure */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource absent (or invisible under the caller's tenant) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description A hard cap was crossed (cloud build only) */
        QuotaExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["QuotaExceeded"];
            };
        };
    };
    parameters: {
        /** @description app.sites.id */
        SiteID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                    };
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The verified claims */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The org's sites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sites?: components["schemas"]["Site"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Subdomain label under shippedusercontent.com (unique per org).
                     * @example my-docs
                     */
                    slug: string;
                };
            };
        };
        responses: {
            /** @description Site created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["QuotaExceeded"];
        };
    };
    getSite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description app.sites.id */
                id: components["parameters"]["SiteID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The site */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Site"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    prepareDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description app.sites.id */
                id: components["parameters"]["SiteID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    manifest: components["schemas"]["ManifestFile"][];
                };
            };
        };
        responses: {
            /** @description Missing blobs + presigned upload URLs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        missing?: string[];
                        /** @description sha256 → presigned PUT URL */
                        uploads?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    finalizeDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description app.sites.id */
                id: components["parameters"]["SiteID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    manifest: components["schemas"]["ManifestFile"][];
                    /** @description Whole-deploy content address (sha256, lowercase hex). The version's content_hash + idempotency key. */
                    digest: string;
                };
            };
        };
        responses: {
            /** @description Immutable version created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description app.sites.id */
                id: components["parameters"]["SiteID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    version_id: string;
                };
            };
        };
        responses: {
            /** @description Published; the site is live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uri */
                        live_url?: string;
                        /** Format: uuid */
                        version_id?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
