// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AppAllowlistEntry struct {
	ID              string
	OrgID           string
	SiteID          string
	Email           string
	IsExternal      bool
	ClaimedAt       pgtype.Timestamptz
	ClaimedByUserID *string
	CreatedAt       time.Time
}

type AppAuditLog struct {
	ID         string
	OrgID      string
	ActorUser  *string
	ActorToken *string
	Action     string
	Target     pgtype.Text
	Metadata   []byte
	Ip         *netip.Addr
	RequestID  pgtype.Text
	TraceID    pgtype.Text
	CreatedAt  time.Time
}

type AppDeployToken struct {
	ID        string
	OrgID     string
	TokenHash string
	Scopes    []string
	SiteID    *string
	CreatedAt time.Time
	RevokedAt pgtype.Timestamptz
}

type AppDomain struct {
	ID           string
	OrgID        string
	SiteID       string
	Hostname     string
	VerifyStatus string
	TlsStatus    string
	CfHostnameID pgtype.Text
	DcvRecord    pgtype.Text
	CreatedAt    time.Time
}

type AppHostRoute struct {
	Host      string
	OrgID     string
	SiteID    string
	CreatedAt time.Time
}

type AppOrgBlob struct {
	OrgID       string
	ContentHash string
	SizeBytes   int64
	CreatedAt   time.Time
}

type AppOrgMetum struct {
	ID                   string
	PlanTier             string
	AllowExternalSharing bool
	DefaultVisibility    string
	CreatedAt            time.Time
	OrgStatus            string
	McpEnabled           bool
}

type AppOrgUsage struct {
	OrgID        string
	MembersCount int32
	SitesCount   int32
	StorageBytes int64
	UpdatedAt    time.Time
}

type AppSite struct {
	ID               string
	OrgID            string
	Slug             string
	OwnerUserID      string
	AccessMode       string
	CurrentVersionID *string
	FeedVisible      bool
	Title            pgtype.Text
	Description      pgtype.Text
	CreatedAt        time.Time
}

type AppSiteAccessPolicy struct {
	SiteID       string
	OrgID        string
	Mode         string
	PasswordHash pgtype.Text
	ExpiresAt    pgtype.Timestamptz
	Unlisted     bool
	UpdatedAt    time.Time
}

type AppSiteComment struct {
	ID               string
	OrgID            string
	SiteID           string
	AuthorUserID     string
	Body             string
	MentionedUserIds []string
	CreatedAt        time.Time
}

type AppSiteVersion struct {
	ID          string
	OrgID       string
	SiteID      string
	VersionNo   int32
	Status      string
	R2Prefix    string
	ContentHash string
	SizeBytes   int64
	CreatedBy   string
	CreatedAt   time.Time
}

type AppSiteVote struct {
	SiteID    string
	OrgID     string
	UserID    string
	Value     int16
	CreatedAt time.Time
	UpdatedAt time.Time
}
