// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOrgStorage = `-- name: AddOrgStorage :exec
UPDATE app.org_usage
SET storage_bytes = storage_bytes + $1::bigint,
    updated_at = now()
WHERE org_id = $2
`

type AddOrgStorageParams struct {
	Delta int64
	OrgID string
}

// Increment the org's running storage total by the new-blob delta (called once per
// deploy with the sum of genuinely-new blob sizes).
func (q *Queries) AddOrgStorage(ctx context.Context, arg AddOrgStorageParams) error {
	_, err := q.db.Exec(ctx, addOrgStorage, arg.Delta, arg.OrgID)
	return err
}

const claimAllowlistEntry = `-- name: ClaimAllowlistEntry :exec
UPDATE app.allowlist_entries
SET claimed_at         = COALESCE(claimed_at, now()),
    claimed_by_user_id = COALESCE(claimed_by_user_id, $2)
WHERE id = $1
`

type ClaimAllowlistEntryParams struct {
	ID              string
	ClaimedByUserID *string
}

// Claim a pending grant for the first verified account that matches it: set
// claimed_at + claimed_by_user_id. Idempotent — re-claiming by the same user is a
// no-op; we only set claim fields when still unclaimed so the original claimant
// and timestamp are preserved.
func (q *Queries) ClaimAllowlistEntry(ctx context.Context, arg ClaimAllowlistEntryParams) error {
	_, err := q.db.Exec(ctx, claimAllowlistEntry, arg.ID, arg.ClaimedByUserID)
	return err
}

const countFolderItems = `-- name: CountFolderItems :one
SELECT count(*)::bigint AS n
FROM app.skill_folder_items
WHERE folder_id = $1
`

func (q *Queries) CountFolderItems(ctx context.Context, folderID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFolderItems, folderID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countSitesForOrg = `-- name: CountSitesForOrg :one
SELECT count(*)::bigint AS n
FROM app.sites
WHERE org_id = $1
`

// The number of sites in the active org (the per-ORG cap input, POOLED across all
// members — seats are free, so the lever is org site count). Read under the
// advisory lock above; RLS already scopes it to the active org and we filter by
// org_id to be explicit.
func (q *Queries) CountSitesForOrg(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSitesForOrg, orgID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const countSkillsForOrg = `-- name: CountSkillsForOrg :one
SELECT count(*)::bigint AS n
FROM app.skills
WHERE org_id = $1
`

func (q *Queries) CountSkillsForOrg(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSkillsForOrg, orgID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createSeedSkill = `-- name: CreateSeedSkill :one
INSERT INTO app.skills (org_id, slug, owner_user_id, title, description)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (org_id, slug) DO NOTHING
RETURNING id, org_id, slug, owner_user_id, title, description, current_version_id, created_at
`

type CreateSeedSkillParams struct {
	OrgID       string
	Slug        string
	OwnerUserID string
	Title       pgtype.Text
	Description pgtype.Text
}

// Insert a preset seed skill, or DO NOTHING if the org already has that slug
// (a real user's skill, or this seed from a prior attempt). ON CONFLICT means a
// collision never raises 23505 and aborts the seeding transaction; a no-rows
// result tells the caller to inspect the existing row and skip it unless it is
// our own seed.
func (q *Queries) CreateSeedSkill(ctx context.Context, arg CreateSeedSkillParams) (AppSkill, error) {
	row := q.db.QueryRow(ctx, createSeedSkill,
		arg.OrgID,
		arg.Slug,
		arg.OwnerUserID,
		arg.Title,
		arg.Description,
	)
	var i AppSkill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.CurrentVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createSite = `-- name: CreateSite :one

INSERT INTO app.sites (org_id, slug, owner_user_id, access_mode)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, slug, owner_user_id, access_mode, current_version_id, feed_visible, title, description, created_at
`

type CreateSiteParams struct {
	OrgID       string
	Slug        string
	OwnerUserID string
	AccessMode  string
}

// ===========================================================================
// sites
// ===========================================================================
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (AppSite, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.OrgID,
		arg.Slug,
		arg.OwnerUserID,
		arg.AccessMode,
	)
	var i AppSite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.OwnerUserID,
		&i.AccessMode,
		&i.CurrentVersionID,
		&i.FeedVisible,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createSiteComment = `-- name: CreateSiteComment :one

INSERT INTO app.site_comments (org_id, site_id, author_user_id, body, mentioned_user_ids)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, site_id, author_user_id, body, mentioned_user_ids, created_at
`

type CreateSiteCommentParams struct {
	OrgID            string
	SiteID           string
	AuthorUserID     string
	Body             string
	MentionedUserIds []string
}

// ===========================================================================
// site_comments — org-internal discussion on a shared site, with @mentions
// ===========================================================================
// Add a comment to a site. mentioned_user_ids is the set of tagged org users
// (identity ids). RLS scopes the INSERT to the active org (the WITH CHECK clause
// on the tenant policy rejects a row whose org_id isn't the active tenant).
func (q *Queries) CreateSiteComment(ctx context.Context, arg CreateSiteCommentParams) (AppSiteComment, error) {
	row := q.db.QueryRow(ctx, createSiteComment,
		arg.OrgID,
		arg.SiteID,
		arg.AuthorUserID,
		arg.Body,
		arg.MentionedUserIds,
	)
	var i AppSiteComment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.AuthorUserID,
		&i.Body,
		&i.MentionedUserIds,
		&i.CreatedAt,
	)
	return i, err
}

const createSiteVersion = `-- name: CreateSiteVersion :one
INSERT INTO app.site_versions (
    org_id, site_id, version_no, status, r2_prefix, content_hash, size_bytes, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, site_id, version_no, status, r2_prefix, content_hash, size_bytes, created_by, created_at
`

type CreateSiteVersionParams struct {
	OrgID       string
	SiteID      string
	VersionNo   int32
	Status      string
	R2Prefix    string
	ContentHash string
	SizeBytes   int64
	CreatedBy   string
}

func (q *Queries) CreateSiteVersion(ctx context.Context, arg CreateSiteVersionParams) (AppSiteVersion, error) {
	row := q.db.QueryRow(ctx, createSiteVersion,
		arg.OrgID,
		arg.SiteID,
		arg.VersionNo,
		arg.Status,
		arg.R2Prefix,
		arg.ContentHash,
		arg.SizeBytes,
		arg.CreatedBy,
	)
	var i AppSiteVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.VersionNo,
		&i.Status,
		&i.R2Prefix,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO app.skills (org_id, slug, owner_user_id, title, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, slug, owner_user_id, title, description, current_version_id, created_at
`

type CreateSkillParams struct {
	OrgID       string
	Slug        string
	OwnerUserID string
	Title       pgtype.Text
	Description pgtype.Text
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (AppSkill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.OrgID,
		arg.Slug,
		arg.OwnerUserID,
		arg.Title,
		arg.Description,
	)
	var i AppSkill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.CurrentVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createSkillFolder = `-- name: CreateSkillFolder :one

INSERT INTO app.skill_folders (org_id, slug, title)
VALUES ($1, $2, $3)
RETURNING id, org_id, slug, title, created_at
`

type CreateSkillFolderParams struct {
	OrgID string
	Slug  string
	Title string
}

// ===========================================================================
// skill folders — admin-curated taxonomy + preset flags
// ===========================================================================
func (q *Queries) CreateSkillFolder(ctx context.Context, arg CreateSkillFolderParams) (AppSkillFolder, error) {
	row := q.db.QueryRow(ctx, createSkillFolder, arg.OrgID, arg.Slug, arg.Title)
	var i AppSkillFolder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const createSkillVersion = `-- name: CreateSkillVersion :one
INSERT INTO app.skill_versions (
    org_id, skill_id, version_no, status, content_hash, size_bytes, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, org_id, skill_id, version_no, status, content_hash, size_bytes, created_by, created_at
`

type CreateSkillVersionParams struct {
	OrgID       string
	SkillID     string
	VersionNo   int32
	Status      string
	ContentHash string
	SizeBytes   int64
	CreatedBy   string
}

func (q *Queries) CreateSkillVersion(ctx context.Context, arg CreateSkillVersionParams) (AppSkillVersion, error) {
	row := q.db.QueryRow(ctx, createSkillVersion,
		arg.OrgID,
		arg.SkillID,
		arg.VersionNo,
		arg.Status,
		arg.ContentHash,
		arg.SizeBytes,
		arg.CreatedBy,
	)
	var i AppSkillVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SkillID,
		&i.VersionNo,
		&i.Status,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAllowlistEntry = `-- name: DeleteAllowlistEntry :exec
DELETE FROM app.allowlist_entries
WHERE site_id = $1 AND email = $2
`

type DeleteAllowlistEntryParams struct {
	SiteID string
	Email  string
}

func (q *Queries) DeleteAllowlistEntry(ctx context.Context, arg DeleteAllowlistEntryParams) error {
	_, err := q.db.Exec(ctx, deleteAllowlistEntry, arg.SiteID, arg.Email)
	return err
}

const deleteDomain = `-- name: DeleteDomain :one
DELETE FROM app.domains
WHERE id = $1
RETURNING id, org_id, site_id, hostname, cf_hostname_id
`

type DeleteDomainRow struct {
	ID           string
	OrgID        string
	SiteID       string
	Hostname     string
	CfHostnameID pgtype.Text
}

// Remove a custom domain, returning its hostname + cf_hostname_id so the caller can
// also drop the global host route (so serve/edge stop resolving the host) and delete
// the Cloudflare custom hostname. RLS scopes the delete to the active org.
func (q *Queries) DeleteDomain(ctx context.Context, id string) (DeleteDomainRow, error) {
	row := q.db.QueryRow(ctx, deleteDomain, id)
	var i DeleteDomainRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Hostname,
		&i.CfHostnameID,
	)
	return i, err
}

const deleteExternalAllowlistEntriesForOrg = `-- name: DeleteExternalAllowlistEntriesForOrg :exec
DELETE FROM app.allowlist_entries
WHERE is_external = true
`

// Remove every external-email allowlist grant in the active org (reconcile on
// disabling external sharing — revoke external access).
func (q *Queries) DeleteExternalAllowlistEntriesForOrg(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExternalAllowlistEntriesForOrg)
	return err
}

const deleteHostRoute = `-- name: DeleteHostRoute :exec
DELETE FROM app.host_routes WHERE host = $1
`

func (q *Queries) DeleteHostRoute(ctx context.Context, host string) error {
	_, err := q.db.Exec(ctx, deleteHostRoute, host)
	return err
}

const deleteOrgBlob = `-- name: DeleteOrgBlob :one
DELETE FROM app.org_blobs
WHERE org_id = $1 AND content_hash = $2
RETURNING size_bytes
`

type DeleteOrgBlobParams struct {
	OrgID       string
	ContentHash string
}

// Drop a blob's ledger row when GC removes the orphaned R2 object; RETURNING the
// size lets the caller decrement the running total. No row = it wasn't in the
// ledger (e.g. uploaded before metering existed) → nothing to decrement.
func (q *Queries) DeleteOrgBlob(ctx context.Context, arg DeleteOrgBlobParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteOrgBlob, arg.OrgID, arg.ContentHash)
	var size_bytes int64
	err := row.Scan(&size_bytes)
	return size_bytes, err
}

const deleteSiteVote = `-- name: DeleteSiteVote :exec
DELETE FROM app.site_votes
WHERE site_id = $1 AND user_id = $2
`

type DeleteSiteVoteParams struct {
	SiteID string
	UserID string
}

// Remove the caller's vote on a site (un-vote). RLS scopes the delete to the org.
func (q *Queries) DeleteSiteVote(ctx context.Context, arg DeleteSiteVoteParams) error {
	_, err := q.db.Exec(ctx, deleteSiteVote, arg.SiteID, arg.UserID)
	return err
}

const deleteSkill = `-- name: DeleteSkill :one
DELETE FROM app.skills
WHERE id = $1
RETURNING id
`

// Remove a skill (versions + folder memberships cascade). RETURNING detects an
// RLS-invisible / absent row as a no-rows miss (→ ErrNotFound).
func (q *Queries) DeleteSkill(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteSkill, id)
	err := row.Scan(&id)
	return id, err
}

const deleteSkillFolder = `-- name: DeleteSkillFolder :one
DELETE FROM app.skill_folders
WHERE id = $1
RETURNING id
`

// Memberships cascade; the skills themselves survive.
func (q *Queries) DeleteSkillFolder(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteSkillFolder, id)
	err := row.Scan(&id)
	return id, err
}

const deleteSkillFolderItemsForSkill = `-- name: DeleteSkillFolderItemsForSkill :exec
DELETE FROM app.skill_folder_items
WHERE skill_id = $1
`

// Replace-memberships helper: clear a skill's memberships before re-inserting
// the new set (PUT /skills/{id}/folders semantics), preserving nothing.
func (q *Queries) DeleteSkillFolderItemsForSkill(ctx context.Context, skillID string) error {
	_, err := q.db.Exec(ctx, deleteSkillFolderItemsForSkill, skillID)
	return err
}

const ensureOrgMeta = `-- name: EnsureOrgMeta :exec


INSERT INTO app.org_meta (id)
VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//
// db/sqlc/query.sql
//
// Typed queries for the Go API's `app` schema. sqlc generates a method per
// annotated query into services/api/internal/store/db. Every query here runs
// inside a per-request transaction that has already executed the SET LOCAL
// tenant GUCs (see internal/store + internal/middleware/rlstx), so RLS scopes
// each statement to the active org. These queries therefore carry NO explicit
// org filter beyond what RLS enforces, except where we deliberately re-derive a
// resource's org for the confused-deputy guard.
// ===========================================================================
// org provisioning
// ===========================================================================
// Idempotent upsert of the app-side org anchor (PK = Better Auth organization.id).
// ON CONFLICT DO NOTHING keeps a re-provision a no-op (the dashboard may call
// ensure-org on every request).
func (q *Queries) EnsureOrgMeta(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, ensureOrgMeta, id)
	return err
}

const ensureOrgUsage = `-- name: EnsureOrgUsage :exec
INSERT INTO app.org_usage (org_id)
VALUES ($1)
ON CONFLICT (org_id) DO NOTHING
`

// Idempotent upsert of the per-org counter row backing the quota gate.
func (q *Queries) EnsureOrgUsage(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, ensureOrgUsage, orgID)
	return err
}

const getAllowlistEntryByEmail = `-- name: GetAllowlistEntryByEmail :one
SELECT id, org_id, site_id, email, is_external, claimed_at, claimed_by_user_id, created_at
FROM app.allowlist_entries
WHERE site_id = $1 AND email = $2
`

type GetAllowlistEntryByEmailParams struct {
	SiteID string
	Email  string
}

// Look up a grant by (site, email) for the authz claim path.
func (q *Queries) GetAllowlistEntryByEmail(ctx context.Context, arg GetAllowlistEntryByEmailParams) (AppAllowlistEntry, error) {
	row := q.db.QueryRow(ctx, getAllowlistEntryByEmail, arg.SiteID, arg.Email)
	var i AppAllowlistEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Email,
		&i.IsExternal,
		&i.ClaimedAt,
		&i.ClaimedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getDomain = `-- name: GetDomain :one
SELECT id, org_id, site_id, hostname, verify_status, tls_status, cf_hostname_id, dcv_record, created_at
FROM app.domains
WHERE id = $1
`

func (q *Queries) GetDomain(ctx context.Context, id string) (AppDomain, error) {
	row := q.db.QueryRow(ctx, getDomain, id)
	var i AppDomain
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Hostname,
		&i.VerifyStatus,
		&i.TlsStatus,
		&i.CfHostnameID,
		&i.DcvRecord,
		&i.CreatedAt,
	)
	return i, err
}

const getHostRoute = `-- name: GetHostRoute :one
SELECT host, org_id, site_id, created_at
FROM app.host_routes
WHERE host = $1
`

// Read the host's owning (org, site). Under the per-tx RLS tenant context this
// returns a row ONLY if the active org owns the host; another org's row (or an
// absent host) is a no-rows miss. Used by Publish / the projection writers to
// assert the publishing site OWNS the host before writing route:<host>.
func (q *Queries) GetHostRoute(ctx context.Context, host string) (AppHostRoute, error) {
	row := q.db.QueryRow(ctx, getHostRoute, host)
	var i AppHostRoute
	err := row.Scan(
		&i.Host,
		&i.OrgID,
		&i.SiteID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateSkillFolder = `-- name: GetOrCreateSkillFolder :one
INSERT INTO app.skill_folders (org_id, slug, title)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, slug) DO UPDATE
SET title = app.skill_folders.title
RETURNING id, org_id, slug, title, created_at
`

type GetOrCreateSkillFolderParams struct {
	OrgID string
	Slug  string
	Title string
}

// Get-or-create a folder by (org_id, slug): a no-op DO UPDATE so RETURNING
// always yields the row. Used by idempotent seeding so re-running against an
// org that already has a default folder (e.g. an admin created it first) never
// raises 23505 and aborts the seed transaction.
func (q *Queries) GetOrCreateSkillFolder(ctx context.Context, arg GetOrCreateSkillFolderParams) (AppSkillFolder, error) {
	row := q.db.QueryRow(ctx, getOrCreateSkillFolder, arg.OrgID, arg.Slug, arg.Title)
	var i AppSkillFolder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgMeta = `-- name: GetOrgMeta :one
SELECT id, plan_tier, allow_external_sharing, default_visibility, created_at, mcp_enabled
FROM app.org_meta
WHERE id = $1
`

type GetOrgMetaRow struct {
	ID                   string
	PlanTier             string
	AllowExternalSharing bool
	DefaultVisibility    string
	CreatedAt            time.Time
	McpEnabled           bool
}

func (q *Queries) GetOrgMeta(ctx context.Context, id string) (GetOrgMetaRow, error) {
	row := q.db.QueryRow(ctx, getOrgMeta, id)
	var i GetOrgMetaRow
	err := row.Scan(
		&i.ID,
		&i.PlanTier,
		&i.AllowExternalSharing,
		&i.DefaultVisibility,
		&i.CreatedAt,
		&i.McpEnabled,
	)
	return i, err
}

const getOrgSkillsSeeded = `-- name: GetOrgSkillsSeeded :one
SELECT COALESCE(
    (SELECT skills_seeded FROM app.org_meta WHERE id = $1),
    false
)::boolean AS skills_seeded
`

func (q *Queries) GetOrgSkillsSeeded(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, getOrgSkillsSeeded, id)
	var skills_seeded bool
	err := row.Scan(&skills_seeded)
	return skills_seeded, err
}

const getOrgStorage = `-- name: GetOrgStorage :one
SELECT COALESCE(
    (SELECT storage_bytes FROM app.org_usage WHERE org_id = $1),
    0
)::bigint AS storage_bytes
`

// The org's current stored bytes (the storage cap-check input). 0 when the
// org_usage row is somehow absent (fail-soft, like GetPlanTier).
func (q *Queries) GetOrgStorage(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, getOrgStorage, orgID)
	var storage_bytes int64
	err := row.Scan(&storage_bytes)
	return storage_bytes, err
}

const getOrgUsage = `-- name: GetOrgUsage :one
SELECT org_id, members_count, sites_count, updated_at
FROM app.org_usage
WHERE org_id = $1
`

type GetOrgUsageRow struct {
	OrgID        string
	MembersCount int32
	SitesCount   int32
	UpdatedAt    time.Time
}

func (q *Queries) GetOrgUsage(ctx context.Context, orgID string) (GetOrgUsageRow, error) {
	row := q.db.QueryRow(ctx, getOrgUsage, orgID)
	var i GetOrgUsageRow
	err := row.Scan(
		&i.OrgID,
		&i.MembersCount,
		&i.SitesCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanTier = `-- name: GetPlanTier :one
SELECT COALESCE(
    (SELECT plan_tier FROM app.org_meta WHERE id = $1),
    'free'
)::text AS plan_tier
`

// The org's live entitlement tier (the authoritative cap-check input). In the
// hosted build org_meta.plan_tier is synced from billing.subscriptions by the
// Stripe webhook; in self-host it stays 'free' but the Unlimited provider ignores
// it. Returns 'free' when the org row is somehow absent (fail-soft default).
func (q *Queries) GetPlanTier(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getPlanTier, id)
	var plan_tier string
	err := row.Scan(&plan_tier)
	return plan_tier, err
}

const getSite = `-- name: GetSite :one
SELECT id, org_id, slug, owner_user_id, access_mode, current_version_id, feed_visible, title, description, created_at
FROM app.sites
WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id string) (AppSite, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i AppSite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.OwnerUserID,
		&i.AccessMode,
		&i.CurrentVersionID,
		&i.FeedVisible,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteAccessPolicy = `-- name: GetSiteAccessPolicy :one
SELECT site_id, org_id, mode, password_hash, expires_at, unlisted, updated_at
FROM app.site_access_policy
WHERE site_id = $1
`

func (q *Queries) GetSiteAccessPolicy(ctx context.Context, siteID string) (AppSiteAccessPolicy, error) {
	row := q.db.QueryRow(ctx, getSiteAccessPolicy, siteID)
	var i AppSiteAccessPolicy
	err := row.Scan(
		&i.SiteID,
		&i.OrgID,
		&i.Mode,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.Unlisted,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteStorageBytes = `-- name: GetSiteStorageBytes :one
SELECT COALESCE(v.size_bytes, 0)::bigint AS bytes
FROM app.sites s
LEFT JOIN app.site_versions v ON v.id = s.current_version_id
WHERE s.id = $1
`

// LOGICAL storage of a single site = the byte size of its CURRENT (live) version
// (site_versions.size_bytes, the sum of that version's file sizes). A site with no
// live version is 0. "Logical" means NOT deduplicated across sites/versions: a file
// shipped by two sites counts in both, the same per-folder model Dropbox/Drive use.
// RLS scopes the read to the active org.
func (q *Queries) GetSiteStorageBytes(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRow(ctx, getSiteStorageBytes, id)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}

const getSiteVersion = `-- name: GetSiteVersion :one
SELECT id, org_id, site_id, version_no, status, r2_prefix, content_hash, size_bytes, created_by, created_at
FROM app.site_versions
WHERE id = $1
`

func (q *Queries) GetSiteVersion(ctx context.Context, id string) (AppSiteVersion, error) {
	row := q.db.QueryRow(ctx, getSiteVersion, id)
	var i AppSiteVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.VersionNo,
		&i.Status,
		&i.R2Prefix,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteVersionByContentHash = `-- name: GetSiteVersionByContentHash :one
SELECT id, org_id, site_id, version_no, status, r2_prefix, content_hash, size_bytes, created_by, created_at
FROM app.site_versions
WHERE site_id = $1 AND content_hash = $2
`

type GetSiteVersionByContentHashParams struct {
	SiteID      string
	ContentHash string
}

// Used to make a re-deploy of identical content idempotent (the per-site
// content_hash unique constraint backs this).
func (q *Queries) GetSiteVersionByContentHash(ctx context.Context, arg GetSiteVersionByContentHashParams) (AppSiteVersion, error) {
	row := q.db.QueryRow(ctx, getSiteVersionByContentHash, arg.SiteID, arg.ContentHash)
	var i AppSiteVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.VersionNo,
		&i.Status,
		&i.R2Prefix,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteVoteScore = `-- name: GetSiteVoteScore :one
SELECT COALESCE(SUM(value), 0)::bigint AS score
FROM app.site_votes
WHERE site_id = $1
`

// A site's net vote score (sum of +1/-1). RLS scopes the read to the active org.
func (q *Queries) GetSiteVoteScore(ctx context.Context, siteID string) (int64, error) {
	row := q.db.QueryRow(ctx, getSiteVoteScore, siteID)
	var score int64
	err := row.Scan(&score)
	return score, err
}

const getSkill = `-- name: GetSkill :one
SELECT sk.id, sk.org_id, sk.slug, sk.owner_user_id, sk.title, sk.description, sk.current_version_id, sk.created_at,
       COALESCE(v.size_bytes, 0)::bigint AS size_bytes
FROM app.skills sk
LEFT JOIN app.skill_versions v ON v.id = sk.current_version_id
WHERE sk.id = $1
`

type GetSkillRow struct {
	AppSkill  AppSkill
	SizeBytes int64
}

// Embeds the full skill row plus its current version's size (0 when unset), so
// reads never N+1 a per-skill version lookup.
func (q *Queries) GetSkill(ctx context.Context, id string) (GetSkillRow, error) {
	row := q.db.QueryRow(ctx, getSkill, id)
	var i GetSkillRow
	err := row.Scan(
		&i.AppSkill.ID,
		&i.AppSkill.OrgID,
		&i.AppSkill.Slug,
		&i.AppSkill.OwnerUserID,
		&i.AppSkill.Title,
		&i.AppSkill.Description,
		&i.AppSkill.CurrentVersionID,
		&i.AppSkill.CreatedAt,
		&i.SizeBytes,
	)
	return i, err
}

const getSkillBySlug = `-- name: GetSkillBySlug :one
SELECT sk.id, sk.org_id, sk.slug, sk.owner_user_id, sk.title, sk.description, sk.current_version_id, sk.created_at,
       COALESCE(v.size_bytes, 0)::bigint AS size_bytes
FROM app.skills sk
LEFT JOIN app.skill_versions v ON v.id = sk.current_version_id
WHERE sk.slug = $1
`

type GetSkillBySlugRow struct {
	AppSkill  AppSkill
	SizeBytes int64
}

func (q *Queries) GetSkillBySlug(ctx context.Context, slug string) (GetSkillBySlugRow, error) {
	row := q.db.QueryRow(ctx, getSkillBySlug, slug)
	var i GetSkillBySlugRow
	err := row.Scan(
		&i.AppSkill.ID,
		&i.AppSkill.OrgID,
		&i.AppSkill.Slug,
		&i.AppSkill.OwnerUserID,
		&i.AppSkill.Title,
		&i.AppSkill.Description,
		&i.AppSkill.CurrentVersionID,
		&i.AppSkill.CreatedAt,
		&i.SizeBytes,
	)
	return i, err
}

const getSkillFolder = `-- name: GetSkillFolder :one
SELECT id, org_id, slug, title, created_at
FROM app.skill_folders
WHERE id = $1
`

func (q *Queries) GetSkillFolder(ctx context.Context, id string) (AppSkillFolder, error) {
	row := q.db.QueryRow(ctx, getSkillFolder, id)
	var i AppSkillFolder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillFolderBySlug = `-- name: GetSkillFolderBySlug :one
SELECT id, org_id, slug, title, created_at
FROM app.skill_folders
WHERE slug = $1
`

func (q *Queries) GetSkillFolderBySlug(ctx context.Context, slug string) (AppSkillFolder, error) {
	row := q.db.QueryRow(ctx, getSkillFolderBySlug, slug)
	var i AppSkillFolder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillVersion = `-- name: GetSkillVersion :one
SELECT id, org_id, skill_id, version_no, status, content_hash, size_bytes, created_by, created_at
FROM app.skill_versions
WHERE id = $1
`

func (q *Queries) GetSkillVersion(ctx context.Context, id string) (AppSkillVersion, error) {
	row := q.db.QueryRow(ctx, getSkillVersion, id)
	var i AppSkillVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SkillID,
		&i.VersionNo,
		&i.Status,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSkillVersionByContentHash = `-- name: GetSkillVersionByContentHash :one
SELECT id, org_id, skill_id, version_no, status, content_hash, size_bytes, created_by, created_at
FROM app.skill_versions
WHERE skill_id = $1 AND content_hash = $2
`

type GetSkillVersionByContentHashParams struct {
	SkillID     string
	ContentHash string
}

// Idempotent re-upload of identical content (the per-skill content_hash unique
// constraint backs this).
func (q *Queries) GetSkillVersionByContentHash(ctx context.Context, arg GetSkillVersionByContentHashParams) (AppSkillVersion, error) {
	row := q.db.QueryRow(ctx, getSkillVersionByContentHash, arg.SkillID, arg.ContentHash)
	var i AppSkillVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SkillID,
		&i.VersionNo,
		&i.Status,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const incSiteCount = `-- name: IncSiteCount :one
UPDATE app.org_usage
SET sites_count = sites_count + 1,
    updated_at  = now()
WHERE org_id = $1
RETURNING sites_count
`

// Bump the org's sites_count counter, returning the new value. Run inside the
// create-site tx after the row is inserted.
func (q *Queries) IncSiteCount(ctx context.Context, orgID string) (int32, error) {
	row := q.db.QueryRow(ctx, incSiteCount, orgID)
	var sites_count int32
	err := row.Scan(&sites_count)
	return sites_count, err
}

const insertDomain = `-- name: InsertDomain :one

INSERT INTO app.domains (org_id, site_id, hostname, verify_status, tls_status, cf_hostname_id, dcv_record)
VALUES ($1, $2, $3, 'pending', 'pending', $4, $5)
RETURNING id, org_id, site_id, hostname, verify_status, tls_status, cf_hostname_id, dcv_record, created_at
`

type InsertDomainParams struct {
	OrgID        string
	SiteID       string
	Hostname     string
	CfHostnameID pgtype.Text
	DcvRecord    pgtype.Text
}

// ===========================================================================
// domains (Phase 2) — Cloudflare-for-SaaS custom hostnames
// ===========================================================================
// Reserve a custom hostname for a site. hostname is GLOBALLY UNIQUE, so a
// conflicting insert from any org raises 23505 (surfaced as ErrHostTaken). Stores
// the Cloudflare custom-hostname id + the DCV record to surface to the user.
func (q *Queries) InsertDomain(ctx context.Context, arg InsertDomainParams) (AppDomain, error) {
	row := q.db.QueryRow(ctx, insertDomain,
		arg.OrgID,
		arg.SiteID,
		arg.Hostname,
		arg.CfHostnameID,
		arg.DcvRecord,
	)
	var i AppDomain
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Hostname,
		&i.VerifyStatus,
		&i.TlsStatus,
		&i.CfHostnameID,
		&i.DcvRecord,
		&i.CreatedAt,
	)
	return i, err
}

const insertHostRoute = `-- name: InsertHostRoute :exec

INSERT INTO app.host_routes (host, org_id, site_id)
VALUES ($1, $2, $3)
`

type InsertHostRouteParams struct {
	Host   string
	OrgID  string
	SiteID string
}

// ===========================================================================
// host_routes (global host registry — the cross-tenant hijack guard)
// ===========================================================================
// Reserve a GLOBAL host for (org, site) inside the CreateSite tx. The PRIMARY KEY
// on host means a host already owned by ANY org raises 23505 (unique_violation),
// which the store surfaces as ErrHostTaken so the whole tx rolls back. RLS scopes
// the row to the active org for later SELECT/UPDATE/DELETE, but the PK guard is
// global regardless of RLS visibility.
func (q *Queries) InsertHostRoute(ctx context.Context, arg InsertHostRouteParams) error {
	_, err := q.db.Exec(ctx, insertHostRoute, arg.Host, arg.OrgID, arg.SiteID)
	return err
}

const insertOrgBlob = `-- name: InsertOrgBlob :one
INSERT INTO app.org_blobs (org_id, content_hash, size_bytes)
VALUES ($1, $2, $3)
ON CONFLICT (org_id, content_hash) DO NOTHING
RETURNING size_bytes
`

type InsertOrgBlobParams struct {
	OrgID       string
	ContentHash string
	SizeBytes   int64
}

// Record a content-addressed blob as stored for the org. Dedup-aware: ON CONFLICT
// DO NOTHING means a blob already present for the org is NOT re-counted — RETURNING
// yields a row (the size) ONLY when the blob is genuinely new, so the caller sums
// the returned sizes as the storage delta. No row (pgx.ErrNoRows) = already stored.
func (q *Queries) InsertOrgBlob(ctx context.Context, arg InsertOrgBlobParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertOrgBlob, arg.OrgID, arg.ContentHash, arg.SizeBytes)
	var size_bytes int64
	err := row.Scan(&size_bytes)
	return size_bytes, err
}

const listAllowlistEntries = `-- name: ListAllowlistEntries :many
SELECT id, org_id, site_id, email, is_external, claimed_at, claimed_by_user_id, created_at
FROM app.allowlist_entries
WHERE site_id = $1
ORDER BY created_at
`

func (q *Queries) ListAllowlistEntries(ctx context.Context, siteID string) ([]AppAllowlistEntry, error) {
	rows, err := q.db.Query(ctx, listAllowlistEntries, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAllowlistEntry{}
	for rows.Next() {
		var i AppAllowlistEntry
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SiteID,
			&i.Email,
			&i.IsExternal,
			&i.ClaimedAt,
			&i.ClaimedByUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, org_id, actor_user, actor_token, action, target, metadata, ip, request_id, trace_id, created_at
FROM app.audit_log
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogParams struct {
	Limit  int32
	Offset int32
}

// Page the active org's audit log newest-first. RLS scopes the read to the org; the
// (org_id, created_at DESC) index backs the order. Keyset-free LIMIT/OFFSET paging is
// adequate for an admin audit viewer (small N per page).
func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AppAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppAuditLog{}
	for rows.Next() {
		var i AppAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorUser,
			&i.ActorToken,
			&i.Action,
			&i.Target,
			&i.Metadata,
			&i.Ip,
			&i.RequestID,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentSkillVersionsForGC = `-- name: ListCurrentSkillVersionsForGC :many

SELECT sk.id AS skill_id, sk.current_version_id AS version_id
FROM app.skills sk
WHERE sk.current_version_id IS NOT NULL
ORDER BY sk.id
`

type ListCurrentSkillVersionsForGCRow struct {
	SkillID   string
	VersionID *string
}

// ===========================================================================
// skills seeding — lazy per-org default folders + preset skills
// ===========================================================================
// Every skill's CURRENT version (latest-only model: that is the only version
// whose blobs must survive GC — superseded skill versions' blobs become
// orphans). The R2 GC unions these manifests' blob refs with the retained site
// versions' refs before deleting unreferenced org blobs; without this, skill
// content would look orphaned to a site-only GC and be deleted. RLS scopes the
// rows to the active org.
func (q *Queries) ListCurrentSkillVersionsForGC(ctx context.Context) ([]ListCurrentSkillVersionsForGCRow, error) {
	rows, err := q.db.Query(ctx, listCurrentSkillVersionsForGC)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentSkillVersionsForGCRow{}
	for rows.Next() {
		var i ListCurrentSkillVersionsForGCRow
		if err := rows.Scan(&i.SkillID, &i.VersionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsForSite = `-- name: ListDomainsForSite :many
SELECT id, org_id, site_id, hostname, verify_status, tls_status, cf_hostname_id, dcv_record, created_at
FROM app.domains
WHERE site_id = $1
ORDER BY created_at
`

func (q *Queries) ListDomainsForSite(ctx context.Context, siteID string) ([]AppDomain, error) {
	rows, err := q.db.Query(ctx, listDomainsForSite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppDomain{}
	for rows.Next() {
		var i AppDomain
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SiteID,
			&i.Hostname,
			&i.VerifyStatus,
			&i.TlsStatus,
			&i.CfHostnameID,
			&i.DcvRecord,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedSites = `-- name: ListFeedSites :many
SELECT
    s.id, s.org_id, s.slug, s.owner_user_id, s.access_mode, s.current_version_id, s.feed_visible, s.title, s.description, s.created_at,
    COALESCE((SELECT SUM(v.value) FROM app.site_votes v WHERE v.site_id = s.id), 0)::bigint AS score,
    COALESCE((SELECT mv.value FROM app.site_votes mv WHERE mv.site_id = s.id AND mv.user_id = $1), 0)::int AS my_vote,
    COALESCE((SELECT COUNT(*) FROM app.site_comments c WHERE c.site_id = s.id), 0)::bigint AS comment_count
FROM app.sites s
WHERE s.feed_visible
ORDER BY s.created_at DESC
`

type ListFeedSitesRow struct {
	AppSite      AppSite
	Score        int64
	MyVote       int32
	CommentCount int64
}

// The org feed: every site in the active org that is feed-visible (not private),
// newest first (older sites sink to the bottom). Each row carries its net vote
// score, the CALLER's own vote ($1 = caller user id; 0 when they haven't voted),
// and its comment count, so the feed renders the up/down controls + counts in one
// query (no N+1). RLS scopes every read (sites, votes, comments) to the active org.
func (q *Queries) ListFeedSites(ctx context.Context, userID string) ([]ListFeedSitesRow, error) {
	rows, err := q.db.Query(ctx, listFeedSites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedSitesRow{}
	for rows.Next() {
		var i ListFeedSitesRow
		if err := rows.Scan(
			&i.AppSite.ID,
			&i.AppSite.OrgID,
			&i.AppSite.Slug,
			&i.AppSite.OwnerUserID,
			&i.AppSite.AccessMode,
			&i.AppSite.CurrentVersionID,
			&i.AppSite.FeedVisible,
			&i.AppSite.Title,
			&i.AppSite.Description,
			&i.AppSite.CreatedAt,
			&i.Score,
			&i.MyVote,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolderSkills = `-- name: ListFolderSkills :many
SELECT sk.id, sk.org_id, sk.slug, sk.owner_user_id, sk.title, sk.description, sk.current_version_id, sk.created_at,
       COALESCE(v.size_bytes, 0)::bigint AS size_bytes
FROM app.skill_folder_items fi
JOIN app.skills sk ON sk.id = fi.skill_id
LEFT JOIN app.skill_versions v ON v.id = sk.current_version_id
WHERE fi.folder_id = $1
  AND sk.current_version_id IS NOT NULL
ORDER BY sk.slug
`

type ListFolderSkillsRow struct {
	AppSkill  AppSkill
	SizeBytes int64
}

// Every skill in a folder that has a live version (the bulk-download set).
func (q *Queries) ListFolderSkills(ctx context.Context, folderID string) ([]ListFolderSkillsRow, error) {
	rows, err := q.db.Query(ctx, listFolderSkills, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFolderSkillsRow{}
	for rows.Next() {
		var i ListFolderSkillsRow
		if err := rows.Scan(
			&i.AppSkill.ID,
			&i.AppSkill.OrgID,
			&i.AppSkill.Slug,
			&i.AppSkill.OwnerUserID,
			&i.AppSkill.Title,
			&i.AppSkill.Description,
			&i.AppSkill.CurrentVersionID,
			&i.AppSkill.CreatedAt,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersForSkills = `-- name: ListFoldersForSkills :many
SELECT fi.skill_id, f.id AS folder_id, f.slug, f.title, fi.is_preset
FROM app.skill_folder_items fi
JOIN app.skill_folders f ON f.id = fi.folder_id
WHERE fi.skill_id = ANY($1::uuid[])
ORDER BY f.slug
`

type ListFoldersForSkillsRow struct {
	SkillID  string
	FolderID string
	Slug     string
	Title    string
	IsPreset bool
}

// Folder memberships for a set of skills in one round-trip (the folder chips on
// each row of a skills listing — no N+1).
func (q *Queries) ListFoldersForSkills(ctx context.Context, skillIds []string) ([]ListFoldersForSkillsRow, error) {
	rows, err := q.db.Query(ctx, listFoldersForSkills, skillIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFoldersForSkillsRow{}
	for rows.Next() {
		var i ListFoldersForSkillsRow
		if err := rows.Scan(
			&i.SkillID,
			&i.FolderID,
			&i.Slug,
			&i.Title,
			&i.IsPreset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHostRoutesForSite = `-- name: ListHostRoutesForSite :many
SELECT host, org_id, site_id, created_at
FROM app.host_routes
WHERE site_id = $1
ORDER BY host
`

// Every host registered for a site in the GLOBAL registry — the canonical
// <slug>.dropwaycontent.com host AND every verified custom-domain host. RLS
// scopes the rows to the active org, so a caller only ever sees its own site's
// hosts. An access-mode / policy change must rewrite EVERY one of these routes
// (not just the canonical one), or a verified custom host keeps serving at the
// OLD access_mode after the policy tightened (revocation).
func (q *Queries) ListHostRoutesForSite(ctx context.Context, siteID string) ([]AppHostRoute, error) {
	rows, err := q.db.Query(ctx, listHostRoutesForSite, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppHostRoute{}
	for rows.Next() {
		var i AppHostRoute
		if err := rows.Scan(
			&i.Host,
			&i.OrgID,
			&i.SiteID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicSitesForOrg = `-- name: ListPublicSitesForOrg :many
SELECT id, org_id, slug, owner_user_id, access_mode, current_version_id, feed_visible, title, description, created_at
FROM app.sites
WHERE access_mode = 'public'
ORDER BY created_at
`

// Every site in the active org whose access_mode = 'public' (used by the reconcile
// on disabling external sharing: these are downgraded to org_only).
func (q *Queries) ListPublicSitesForOrg(ctx context.Context) ([]AppSite, error) {
	rows, err := q.db.Query(ctx, listPublicSitesForOrg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSite{}
	for rows.Next() {
		var i AppSite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.OwnerUserID,
			&i.AccessMode,
			&i.CurrentVersionID,
			&i.FeedVisible,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedSitesForRebuild = `-- name: ListPublishedSitesForRebuild :many

SELECT
    s.id            AS site_id,
    s.org_id        AS org_id,
    s.slug          AS slug,
    s.access_mode   AS access_mode,
    s.current_version_id AS version_id
FROM app.sites s
WHERE s.current_version_id IS NOT NULL
ORDER BY s.created_at
`

type ListPublishedSitesForRebuildRow struct {
	SiteID     string
	OrgID      string
	Slug       string
	AccessMode string
	VersionID  *string
}

// ===========================================================================
// projection rebuild (the "KV is rebuildable from Postgres" invariant)
// ===========================================================================
// Every site that currently has a live version, joined to that version's
// access_mode source (the site row). Drives projection.RebuildFromDB: Postgres
// is authoritative, the KV/D1 projection is a rebuildable cache.
func (q *Queries) ListPublishedSitesForRebuild(ctx context.Context) ([]ListPublishedSitesForRebuildRow, error) {
	rows, err := q.db.Query(ctx, listPublishedSitesForRebuild)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedSitesForRebuildRow{}
	for rows.Next() {
		var i ListPublishedSitesForRebuildRow
		if err := rows.Scan(
			&i.SiteID,
			&i.OrgID,
			&i.Slug,
			&i.AccessMode,
			&i.VersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteComments = `-- name: ListSiteComments :many
SELECT id, org_id, site_id, author_user_id, body, mentioned_user_ids, created_at
FROM (
    SELECT id, org_id, site_id, author_user_id, body, mentioned_user_ids, created_at
    FROM app.site_comments
    WHERE site_id = $1
    ORDER BY created_at DESC, id DESC
    LIMIT $2
) recent
ORDER BY created_at ASC, id ASC
`

type ListSiteCommentsParams struct {
	SiteID string
	Limit  int32
}

// A site's comment thread, displayed oldest-first (top-to-bottom like a
// conversation) but BOUNDED to the most recent $2 comments so a long thread can't
// load an unbounded result. RLS scopes the read to the active org; the
// (site_id, created_at) index backs both the inner ordering and the outer.
func (q *Queries) ListSiteComments(ctx context.Context, arg ListSiteCommentsParams) ([]AppSiteComment, error) {
	rows, err := q.db.Query(ctx, listSiteComments, arg.SiteID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSiteComment{}
	for rows.Next() {
		var i AppSiteComment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SiteID,
			&i.AuthorUserID,
			&i.Body,
			&i.MentionedUserIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteStorageForOrg = `-- name: ListSiteStorageForOrg :many
SELECT
    s.id            AS site_id,
    s.owner_user_id AS owner_user_id,
    COALESCE(v.size_bytes, 0)::bigint AS bytes
FROM app.sites s
LEFT JOIN app.site_versions v ON v.id = s.current_version_id
ORDER BY s.created_at DESC
`

type ListSiteStorageForOrgRow struct {
	SiteID      string
	OwnerUserID string
	Bytes       int64
}

// LOGICAL storage per site for the active org (the current-version size of each
// site, 0 when it has no live version) paired with the owning user, so the caller
// can show per-site usage AND aggregate it per user. Same non-deduplicated model as
// GetSiteStorageBytes. RLS scopes the read to the active org.
func (q *Queries) ListSiteStorageForOrg(ctx context.Context) ([]ListSiteStorageForOrgRow, error) {
	rows, err := q.db.Query(ctx, listSiteStorageForOrg)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteStorageForOrgRow{}
	for rows.Next() {
		var i ListSiteStorageForOrgRow
		if err := rows.Scan(&i.SiteID, &i.OwnerUserID, &i.Bytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteVersions = `-- name: ListSiteVersions :many
SELECT id, org_id, site_id, version_no, status, r2_prefix, content_hash, size_bytes, created_by, created_at
FROM app.site_versions
WHERE site_id = $1
ORDER BY version_no DESC
`

func (q *Queries) ListSiteVersions(ctx context.Context, siteID string) ([]AppSiteVersion, error) {
	rows, err := q.db.Query(ctx, listSiteVersions, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSiteVersion{}
	for rows.Next() {
		var i AppSiteVersion
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SiteID,
			&i.VersionNo,
			&i.Status,
			&i.R2Prefix,
			&i.ContentHash,
			&i.SizeBytes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT id, org_id, slug, owner_user_id, access_mode, current_version_id, feed_visible, title, description, created_at
FROM app.sites
ORDER BY created_at DESC
`

func (q *Queries) ListSites(ctx context.Context) ([]AppSite, error) {
	rows, err := q.db.Query(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSite{}
	for rows.Next() {
		var i AppSite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.OwnerUserID,
			&i.AccessMode,
			&i.CurrentVersionID,
			&i.FeedVisible,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillFolders = `-- name: ListSkillFolders :many
SELECT
    f.id, f.org_id, f.slug, f.title, f.created_at,
    COALESCE((SELECT COUNT(*) FROM app.skill_folder_items fi WHERE fi.folder_id = f.id), 0)::bigint AS item_count
FROM app.skill_folders f
ORDER BY f.slug
`

type ListSkillFoldersRow struct {
	ID        string
	OrgID     string
	Slug      string
	Title     string
	CreatedAt time.Time
	ItemCount int64
}

// The org's folders with their member counts (the folder tabs + admin panel).
func (q *Queries) ListSkillFolders(ctx context.Context) ([]ListSkillFoldersRow, error) {
	rows, err := q.db.Query(ctx, listSkillFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillFoldersRow{}
	for rows.Next() {
		var i ListSkillFoldersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.Title,
			&i.CreatedAt,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkills = `-- name: ListSkills :many
SELECT sk.id, sk.org_id, sk.slug, sk.owner_user_id, sk.title, sk.description, sk.current_version_id, sk.created_at,
       COALESCE(v.size_bytes, 0)::bigint AS size_bytes
FROM app.skills sk
LEFT JOIN app.skill_versions v ON v.id = sk.current_version_id
WHERE (sk.current_version_id IS NOT NULL OR sk.owner_user_id = $1::uuid)
  AND (
        $2::text = ''
        OR sk.slug ILIKE '%' || $2 || '%'
        OR COALESCE(sk.title, '') ILIKE '%' || $2 || '%'
        OR COALESCE(sk.description, '') ILIKE '%' || $2 || '%'
      )
  AND (
        ($3::text = '' AND NOT $4::boolean)
        OR EXISTS (
            SELECT 1
            FROM app.skill_folder_items fi
            JOIN app.skill_folders f ON f.id = fi.folder_id
            WHERE fi.skill_id = sk.id
              AND ($3::text = '' OR f.slug = $3)
              AND (NOT $4::boolean OR fi.is_preset)
        )
      )
ORDER BY sk.created_at DESC
`

type ListSkillsParams struct {
	CallerID    string
	Q           string
	FolderSlug  string
	PresetsOnly bool
}

type ListSkillsRow struct {
	AppSkill  AppSkill
	SizeBytes int64
}

// Search + filter the active org's skills. q matches slug/title/description
// (ILIKE, ” = no text filter); folder_slug restricts to members of that folder
// (” = any); presets_only additionally requires the membership's is_preset flag.
// Skills that have never finalized an upload (no current version) are visible
// only to their owner (caller_id), so half-finished uploads don't clutter the
// org listing. RLS scopes every read to the active org.
func (q *Queries) ListSkills(ctx context.Context, arg ListSkillsParams) ([]ListSkillsRow, error) {
	rows, err := q.db.Query(ctx, listSkills,
		arg.CallerID,
		arg.Q,
		arg.FolderSlug,
		arg.PresetsOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSkillsRow{}
	for rows.Next() {
		var i ListSkillsRow
		if err := rows.Scan(
			&i.AppSkill.ID,
			&i.AppSkill.OrgID,
			&i.AppSkill.Slug,
			&i.AppSkill.OwnerUserID,
			&i.AppSkill.Title,
			&i.AppSkill.Description,
			&i.AppSkill.CurrentVersionID,
			&i.AppSkill.CreatedAt,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionsForGC = `-- name: ListVersionsForGC :many

SELECT
    v.id            AS version_id,
    v.site_id       AS site_id,
    v.version_no    AS version_no,
    v.r2_prefix     AS r2_prefix,
    (s.current_version_id IS NOT NULL AND s.current_version_id = v.id) AS is_current
FROM app.site_versions v
JOIN app.sites s ON s.id = v.site_id
ORDER BY v.site_id, v.version_no DESC
`

type ListVersionsForGCRow struct {
	VersionID string
	SiteID    string
	VersionNo int32
	R2Prefix  string
	IsCurrent pgtype.Bool
}

// ===========================================================================
// R2 version GC (Phase 4) — versions to retain per org
// ===========================================================================
// Every version of every site in the active org, newest first within each site,
// flagged with whether it is the site's CURRENT (live) version. Drives the R2
// version GC retention policy (keep current + last N): the GC groups by site, keeps
// the current version + the top-N by version_no, reads those versions' manifests to
// collect referenced blob shas, and deletes every org blob not in that set. RLS
// scopes the rows to the active org. r2_prefix + id locate the manifest object.
func (q *Queries) ListVersionsForGC(ctx context.Context) ([]ListVersionsForGCRow, error) {
	rows, err := q.db.Query(ctx, listVersionsForGC)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVersionsForGCRow{}
	for rows.Next() {
		var i ListVersionsForGCRow
		if err := rows.Scan(
			&i.VersionID,
			&i.SiteID,
			&i.VersionNo,
			&i.R2Prefix,
			&i.IsCurrent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrgMemberQuota = `-- name: LockOrgMemberQuota :exec
SELECT pg_advisory_xact_lock(hashtext($1::text || ':members'))
`

// Serialize the members-cap preflight for an org: a transaction-scoped advisory
// lock keyed by hashtext(org||':members'). Best-effort server-side enforcement on
// OUR code path (Better Auth actually inserts the member row), so the lock just
// makes our COUNT → policy check coherent under concurrent preflights.
func (q *Queries) LockOrgMemberQuota(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockOrgMemberQuota, dollar_1)
	return err
}

const lockOrgSiteQuota = `-- name: LockOrgSiteQuota :exec
SELECT pg_advisory_xact_lock(hashtext($1::text || ':sites'))
`

// Serialize concurrent site creates for the SAME org: take a transaction-scoped
// advisory lock keyed by hashtext(org||':sites'). Held until the create-site tx
// commits/rolls back, it makes the COUNT → policy check → INSERT a critical
// section, so two racing creates anywhere in the org can't both read current=N and
// both insert (the TOCTOU the per-ORG cap must not allow). Advisory locks are
// independent of RLS and of row locks, so this needs no rows to exist yet.
func (q *Queries) LockOrgSiteQuota(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockOrgSiteQuota, dollar_1)
	return err
}

const lockOrgSkillQuota = `-- name: LockOrgSkillQuota :exec

SELECT pg_advisory_xact_lock(hashtext($1::text || ':skills'))
`

// ===========================================================================
// skills (migration 0008) — org-wide skill sharing
// ===========================================================================
// Serialize concurrent skill creates for the SAME org (the same COUNT → policy →
// INSERT critical section the site cap uses).
func (q *Queries) LockOrgSkillQuota(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockOrgSkillQuota, dollar_1)
	return err
}

const lockOrgSkillsSeed = `-- name: LockOrgSkillsSeed :exec
SELECT pg_advisory_xact_lock(hashtext($1::text || ':skills_seed'))
`

// Serialize concurrent first-touches of the skills feature for an org, so the
// skills_seeded check → seed → set-flag sequence runs exactly once.
func (q *Queries) LockOrgSkillsSeed(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockOrgSkillsSeed, dollar_1)
	return err
}

const lockOrgStorageQuota = `-- name: LockOrgStorageQuota :exec

SELECT pg_advisory_xact_lock(hashtext($1::text || ':storage'))
`

// ===========================================================================
// storage metering: org_blobs ledger + org_usage counter
// ===========================================================================
// Serialize concurrent deploys' storage accounting for an org: a transaction-scoped
// advisory lock keyed by hashtext(org||':storage'), so the GetOrgStorage → cap check
// → ledger INSERT → counter UPDATE is a critical section (the same TOCTOU guard the
// site cap uses). Held until the deploy tx commits/rolls back.
func (q *Queries) LockOrgStorageQuota(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockOrgStorageQuota, dollar_1)
	return err
}

const lockSkillFolderQuota = `-- name: LockSkillFolderQuota :exec
SELECT pg_advisory_xact_lock(hashtext($1::text || ':folder_items'))
`

// Serialize concurrent membership inserts for the SAME folder, so the COUNT →
// per-folder cap check → INSERT is a critical section (free tier caps skills per
// folder; see quota.ResourceSkillPerFolder).
func (q *Queries) LockSkillFolderQuota(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockSkillFolderQuota, dollar_1)
	return err
}

const nextSkillVersionNo = `-- name: NextSkillVersionNo :one
SELECT COALESCE(MAX(version_no), 0) + 1 AS next_version_no
FROM app.skill_versions
WHERE skill_id = $1
`

func (q *Queries) NextSkillVersionNo(ctx context.Context, skillID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextSkillVersionNo, skillID)
	var next_version_no int32
	err := row.Scan(&next_version_no)
	return next_version_no, err
}

const nextVersionNo = `-- name: NextVersionNo :one

SELECT COALESCE(MAX(version_no), 0) + 1 AS next_version_no
FROM app.site_versions
WHERE site_id = $1
`

// ===========================================================================
// site_versions
// ===========================================================================
// The next monotonic version number for a site (1 on the first deploy).
func (q *Queries) NextVersionNo(ctx context.Context, siteID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextVersionNo, siteID)
	var next_version_no int32
	err := row.Scan(&next_version_no)
	return next_version_no, err
}

const recomputeOrgStorage = `-- name: RecomputeOrgStorage :exec
UPDATE app.org_usage
SET storage_bytes = COALESCE(
        (SELECT SUM(b.size_bytes) FROM app.org_blobs b WHERE b.org_id = $1), 0),
    updated_at = now()
WHERE app.org_usage.org_id = $1
`

// Reconcile the running total to the authoritative ledger sum (the cheap drift
// fix; a deeper audit lists R2 to prune ledger rows orphaned by a crashed GC).
func (q *Queries) RecomputeOrgStorage(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, recomputeOrgStorage, orgID)
	return err
}

const removeSkillFolderItem = `-- name: RemoveSkillFolderItem :one
DELETE FROM app.skill_folder_items
WHERE folder_id = $1 AND skill_id = $2
RETURNING skill_id
`

type RemoveSkillFolderItemParams struct {
	FolderID string
	SkillID  string
}

func (q *Queries) RemoveSkillFolderItem(ctx context.Context, arg RemoveSkillFolderItemParams) (string, error) {
	row := q.db.QueryRow(ctx, removeSkillFolderItem, arg.FolderID, arg.SkillID)
	var skill_id string
	err := row.Scan(&skill_id)
	return skill_id, err
}

const renameSkillFolder = `-- name: RenameSkillFolder :one
UPDATE app.skill_folders
SET title = $2
WHERE id = $1
RETURNING id, org_id, slug, title, created_at
`

type RenameSkillFolderParams struct {
	ID    string
	Title string
}

func (q *Queries) RenameSkillFolder(ctx context.Context, arg RenameSkillFolderParams) (AppSkillFolder, error) {
	row := q.db.QueryRow(ctx, renameSkillFolder, arg.ID, arg.Title)
	var i AppSkillFolder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const resolveSiteByHostRoute = `-- name: ResolveSiteByHostRoute :one

SELECT
    hr.host       AS host,
    s.id          AS site_id,
    s.org_id      AS org_id,
    s.slug        AS slug,
    s.access_mode AS access_mode,
    s.current_version_id AS version_id
FROM app.host_routes hr
JOIN app.sites s ON s.id = hr.site_id
WHERE hr.host = $1
`

type ResolveSiteByHostRouteRow struct {
	Host       string
	SiteID     string
	OrgID      string
	Slug       string
	AccessMode string
	VersionID  *string
}

// ===========================================================================
// host resolution (Phase 2) — resolve a content host → owning site (for /authz)
// ===========================================================================
// Resolve a content host (the *.dropwaycontent.com label OR a verified custom
// host) to its owning site via the global host registry, returning the site's
// access fields. Runs under RLS so only the active org's hosts resolve — the
// /authz mint sets the tenant from the resolved org first (see store.AuthzContext).
func (q *Queries) ResolveSiteByHostRoute(ctx context.Context, host string) (ResolveSiteByHostRouteRow, error) {
	row := q.db.QueryRow(ctx, resolveSiteByHostRoute, host)
	var i ResolveSiteByHostRouteRow
	err := row.Scan(
		&i.Host,
		&i.SiteID,
		&i.OrgID,
		&i.Slug,
		&i.AccessMode,
		&i.VersionID,
	)
	return i, err
}

const setAllowExternalSharing = `-- name: SetAllowExternalSharing :exec

UPDATE app.org_meta
SET allow_external_sharing = $2
WHERE id = $1
`

type SetAllowExternalSharingParams struct {
	ID                   string
	AllowExternalSharing bool
}

// ===========================================================================
// org policy (Phase 2) — allow_external_sharing toggle + reconcile
// ===========================================================================
// Toggle the org's external-sharing policy (admin/owner only, enforced in Go).
func (q *Queries) SetAllowExternalSharing(ctx context.Context, arg SetAllowExternalSharingParams) error {
	_, err := q.db.Exec(ctx, setAllowExternalSharing, arg.ID, arg.AllowExternalSharing)
	return err
}

const setCurrentVersion = `-- name: SetCurrentVersion :exec
UPDATE app.sites
SET current_version_id = $2
WHERE id = $1
`

type SetCurrentVersionParams struct {
	ID               string
	CurrentVersionID *string
}

// Flip the live-version pointer (publish / rollback). RLS guarantees we can only
// touch our own org's site; we also re-check the version belongs to the site.
func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}

const setMcpEnabled = `-- name: SetMcpEnabled :exec
UPDATE app.org_meta
SET mcp_enabled = $2
WHERE id = $1
`

type SetMcpEnabledParams struct {
	ID         string
	McpEnabled bool
}

// Toggle whether the Dropway MCP server may serve this org (admin/owner only,
// enforced in Go). The MCP resource server ALSO re-checks org_meta.mcp_enabled per
// request, so disabling takes effect immediately even for already-issued tokens.
func (q *Queries) SetMcpEnabled(ctx context.Context, arg SetMcpEnabledParams) error {
	_, err := q.db.Exec(ctx, setMcpEnabled, arg.ID, arg.McpEnabled)
	return err
}

const setOrgSkillsSeeded = `-- name: SetOrgSkillsSeeded :exec
UPDATE app.org_meta
SET skills_seeded = $2
WHERE id = $1
`

type SetOrgSkillsSeededParams struct {
	ID           string
	SkillsSeeded bool
}

func (q *Queries) SetOrgSkillsSeeded(ctx context.Context, arg SetOrgSkillsSeededParams) error {
	_, err := q.db.Exec(ctx, setOrgSkillsSeeded, arg.ID, arg.SkillsSeeded)
	return err
}

const setSiteAccessMode = `-- name: SetSiteAccessMode :exec

UPDATE app.sites
SET access_mode = $2
WHERE id = $1
`

type SetSiteAccessModeParams struct {
	ID         string
	AccessMode string
}

// ===========================================================================
// access policy (Phase 2) — per-site gating config
// ===========================================================================
// Flip a site's access_mode (the source for the edge RouteValue). RLS scopes the
// UPDATE to the active org; the external-sharing trigger (0004) rejects 'public'
// under a false org policy.
func (q *Queries) SetSiteAccessMode(ctx context.Context, arg SetSiteAccessModeParams) error {
	_, err := q.db.Exec(ctx, setSiteAccessMode, arg.ID, arg.AccessMode)
	return err
}

const setSiteFeedMeta = `-- name: SetSiteFeedMeta :one
UPDATE app.sites
SET title       = $2,
    description  = $3
WHERE id = $1
RETURNING id, org_id, slug, owner_user_id, access_mode, current_version_id, feed_visible, title, description, created_at
`

type SetSiteFeedMetaParams struct {
	ID          string
	Title       pgtype.Text
	Description pgtype.Text
}

// Set a site's human feed metadata (title + description). Empty strings are passed
// as NULL by the caller so "clear it" round-trips to a null column. RLS scopes the
// UPDATE to the active org; the handler restricts it to the owner or an org admin.
func (q *Queries) SetSiteFeedMeta(ctx context.Context, arg SetSiteFeedMetaParams) (AppSite, error) {
	row := q.db.QueryRow(ctx, setSiteFeedMeta, arg.ID, arg.Title, arg.Description)
	var i AppSite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.OwnerUserID,
		&i.AccessMode,
		&i.CurrentVersionID,
		&i.FeedVisible,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const setSiteFeedVisible = `-- name: SetSiteFeedVisible :one
UPDATE app.sites
SET feed_visible = $2
WHERE id = $1
RETURNING id, org_id, slug, owner_user_id, access_mode, current_version_id, feed_visible, title, description, created_at
`

type SetSiteFeedVisibleParams struct {
	ID          string
	FeedVisible bool
}

// Mark a site shared-to-feed (true) or private/off-feed (false). RLS scopes the
// UPDATE to the active org; the handler additionally restricts it to the site's
// owner or an org admin/owner. Does NOT touch access_mode, so the edge projection
// is unaffected (feed visibility is the discovery axis, not the access axis).
func (q *Queries) SetSiteFeedVisible(ctx context.Context, arg SetSiteFeedVisibleParams) (AppSite, error) {
	row := q.db.QueryRow(ctx, setSiteFeedVisible, arg.ID, arg.FeedVisible)
	var i AppSite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.OwnerUserID,
		&i.AccessMode,
		&i.CurrentVersionID,
		&i.FeedVisible,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const setSkillCurrentVersion = `-- name: SetSkillCurrentVersion :exec
UPDATE app.skills
SET current_version_id = $2
WHERE id = $1
`

type SetSkillCurrentVersionParams struct {
	ID               string
	CurrentVersionID *string
}

// Flip the live pointer (finalize = publish in the latest-only v1 model).
func (q *Queries) SetSkillCurrentVersion(ctx context.Context, arg SetSkillCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setSkillCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}

const setSkillFolderItemPreset = `-- name: SetSkillFolderItemPreset :one
UPDATE app.skill_folder_items
SET is_preset = $3
WHERE folder_id = $1 AND skill_id = $2
RETURNING folder_id, skill_id, is_preset
`

type SetSkillFolderItemPresetParams struct {
	FolderID string
	SkillID  string
	IsPreset bool
}

type SetSkillFolderItemPresetRow struct {
	FolderID string
	SkillID  string
	IsPreset bool
}

func (q *Queries) SetSkillFolderItemPreset(ctx context.Context, arg SetSkillFolderItemPresetParams) (SetSkillFolderItemPresetRow, error) {
	row := q.db.QueryRow(ctx, setSkillFolderItemPreset, arg.FolderID, arg.SkillID, arg.IsPreset)
	var i SetSkillFolderItemPresetRow
	err := row.Scan(&i.FolderID, &i.SkillID, &i.IsPreset)
	return i, err
}

const setSkillMeta = `-- name: SetSkillMeta :one
UPDATE app.skills
SET title = $2,
    description = $3
WHERE id = $1
RETURNING id, org_id, slug, owner_user_id, title, description, current_version_id, created_at
`

type SetSkillMetaParams struct {
	ID          string
	Title       pgtype.Text
	Description pgtype.Text
}

// Fill a skill's human metadata (from SKILL.md frontmatter on finalize, or an
// explicit edit). Empty strings are passed as NULL so "unset" round-trips.
func (q *Queries) SetSkillMeta(ctx context.Context, arg SetSkillMetaParams) (AppSkill, error) {
	row := q.db.QueryRow(ctx, setSkillMeta, arg.ID, arg.Title, arg.Description)
	var i AppSkill
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.OwnerUserID,
		&i.Title,
		&i.Description,
		&i.CurrentVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const subOrgStorage = `-- name: SubOrgStorage :exec
UPDATE app.org_usage
SET storage_bytes = GREATEST(0, storage_bytes - $1::bigint),
    updated_at = now()
WHERE org_id = $2
`

type SubOrgStorageParams struct {
	Delta int64
	OrgID string
}

// Decrement the org's running storage total by the freed bytes (GC). GREATEST(0,…)
// floors at zero so a reconciliation skew can never make the counter negative.
func (q *Queries) SubOrgStorage(ctx context.Context, arg SubOrgStorageParams) error {
	_, err := q.db.Exec(ctx, subOrgStorage, arg.Delta, arg.OrgID)
	return err
}

const updateDomainStatus = `-- name: UpdateDomainStatus :one
UPDATE app.domains
SET verify_status = $2,
    tls_status    = $3
WHERE id = $1
RETURNING id, org_id, site_id, hostname, verify_status, tls_status, cf_hostname_id, dcv_record, created_at
`

type UpdateDomainStatusParams struct {
	ID           string
	VerifyStatus string
	TlsStatus    string
}

// Advance the custom-domain state machine (pending → verifying → verified/failed)
// and the TLS status from a Cloudflare Status() poll.
func (q *Queries) UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) (AppDomain, error) {
	row := q.db.QueryRow(ctx, updateDomainStatus, arg.ID, arg.VerifyStatus, arg.TlsStatus)
	var i AppDomain
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Hostname,
		&i.VerifyStatus,
		&i.TlsStatus,
		&i.CfHostnameID,
		&i.DcvRecord,
		&i.CreatedAt,
	)
	return i, err
}

const upsertAllowlistEntry = `-- name: UpsertAllowlistEntry :one

INSERT INTO app.allowlist_entries (org_id, site_id, email, is_external)
VALUES ($1, $2, $3, $4)
ON CONFLICT (site_id, email) DO UPDATE
SET is_external        = EXCLUDED.is_external,
    claimed_at         = NULL,
    claimed_by_user_id = NULL
RETURNING id, org_id, site_id, email, is_external, claimed_at, claimed_by_user_id, created_at
`

type UpsertAllowlistEntryParams struct {
	OrgID      string
	SiteID     string
	Email      string
	IsExternal bool
}

// ===========================================================================
// allowlist (Phase 2)
// ===========================================================================
// Add (or re-add) an email grant to a site's allowlist. is_external marks an
// email whose domain is not an org verified domain; the external-sharing trigger
// (0004) rejects is_external=true under a false org policy. Re-adding an email
// resets it to a fresh pending (unclaimed) grant.
func (q *Queries) UpsertAllowlistEntry(ctx context.Context, arg UpsertAllowlistEntryParams) (AppAllowlistEntry, error) {
	row := q.db.QueryRow(ctx, upsertAllowlistEntry,
		arg.OrgID,
		arg.SiteID,
		arg.Email,
		arg.IsExternal,
	)
	var i AppAllowlistEntry
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.Email,
		&i.IsExternal,
		&i.ClaimedAt,
		&i.ClaimedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const upsertHostRoute = `-- name: UpsertHostRoute :exec

INSERT INTO app.host_routes (host, org_id, site_id)
VALUES ($1, $2, $3)
ON CONFLICT (host) DO UPDATE
SET site_id = EXCLUDED.site_id
WHERE app.host_routes.org_id = EXCLUDED.org_id
`

type UpsertHostRouteParams struct {
	Host   string
	OrgID  string
	SiteID string
}

// ===========================================================================
// host_routes (Phase 2) — register/unregister a custom host in the global registry
// ===========================================================================
// Register a host → (org, site) in the GLOBAL registry. Used when a custom domain
// verifies (the content host is the custom hostname). PK on host enforces global
// uniqueness; a conflict with another org raises 23505 (ErrHostTaken). ON CONFLICT
// updates only when the row is already owned by THIS (org, site) — a different
// owner can never be overwritten because RLS makes its row invisible to UPDATE, so
// the ON CONFLICT target row isn't visible and the upsert raises instead.
func (q *Queries) UpsertHostRoute(ctx context.Context, arg UpsertHostRouteParams) error {
	_, err := q.db.Exec(ctx, upsertHostRoute, arg.Host, arg.OrgID, arg.SiteID)
	return err
}

const upsertSiteAccessPolicy = `-- name: UpsertSiteAccessPolicy :one
INSERT INTO app.site_access_policy (site_id, org_id, mode, password_hash, expires_at, unlisted, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (site_id) DO UPDATE
SET mode          = EXCLUDED.mode,
    password_hash = EXCLUDED.password_hash,
    expires_at    = EXCLUDED.expires_at,
    unlisted      = EXCLUDED.unlisted,
    updated_at    = now()
RETURNING site_id, org_id, mode, password_hash, expires_at, unlisted, updated_at
`

type UpsertSiteAccessPolicyParams struct {
	SiteID       string
	OrgID        string
	Mode         string
	PasswordHash pgtype.Text
	ExpiresAt    pgtype.Timestamptz
	Unlisted     bool
}

// Insert or replace the per-site access policy (one row per site, PK = site_id).
// password_hash is non-null only for mode='password'; expires_at / unlisted are
// optional. The policy-mirror external-sharing trigger (0004) rejects mode='public'
// under a false org policy.
func (q *Queries) UpsertSiteAccessPolicy(ctx context.Context, arg UpsertSiteAccessPolicyParams) (AppSiteAccessPolicy, error) {
	row := q.db.QueryRow(ctx, upsertSiteAccessPolicy,
		arg.SiteID,
		arg.OrgID,
		arg.Mode,
		arg.PasswordHash,
		arg.ExpiresAt,
		arg.Unlisted,
	)
	var i AppSiteAccessPolicy
	err := row.Scan(
		&i.SiteID,
		&i.OrgID,
		&i.Mode,
		&i.PasswordHash,
		&i.ExpiresAt,
		&i.Unlisted,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSiteVote = `-- name: UpsertSiteVote :exec
INSERT INTO app.site_votes (site_id, org_id, user_id, value)
VALUES ($1, $2, $3, $4)
ON CONFLICT (site_id, user_id) DO UPDATE
SET value = EXCLUDED.value, updated_at = now()
`

type UpsertSiteVoteParams struct {
	SiteID string
	OrgID  string
	UserID string
	Value  int16
}

// Cast (or change) the caller's vote on a site. One row per (site, user); a flip
// from up to down just overwrites value. RLS scopes the write to the active org.
func (q *Queries) UpsertSiteVote(ctx context.Context, arg UpsertSiteVoteParams) error {
	_, err := q.db.Exec(ctx, upsertSiteVote,
		arg.SiteID,
		arg.OrgID,
		arg.UserID,
		arg.Value,
	)
	return err
}

const upsertSkillFolderItem = `-- name: UpsertSkillFolderItem :exec
INSERT INTO app.skill_folder_items (org_id, folder_id, skill_id, is_preset, added_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (folder_id, skill_id) DO UPDATE
SET is_preset = EXCLUDED.is_preset
`

type UpsertSkillFolderItemParams struct {
	OrgID    string
	FolderID string
	SkillID  string
	IsPreset bool
	AddedBy  string
}

// Add a skill to a folder (or update its preset flag if already a member).
func (q *Queries) UpsertSkillFolderItem(ctx context.Context, arg UpsertSkillFolderItemParams) error {
	_, err := q.db.Exec(ctx, upsertSkillFolderItem,
		arg.OrgID,
		arg.FolderID,
		arg.SkillID,
		arg.IsPreset,
		arg.AddedBy,
	)
	return err
}

const upsertSkillVersion = `-- name: UpsertSkillVersion :one
INSERT INTO app.skill_versions (
    org_id, skill_id, version_no, status, content_hash, size_bytes, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (skill_id, content_hash) DO UPDATE
SET status = app.skill_versions.status
RETURNING id, org_id, skill_id, version_no, status, content_hash, size_bytes, created_by, created_at
`

type UpsertSkillVersionParams struct {
	OrgID       string
	SkillID     string
	VersionNo   int32
	Status      string
	ContentHash string
	SizeBytes   int64
	CreatedBy   string
}

// Get-or-create a version by its (skill_id, content_hash): a no-op DO UPDATE so
// RETURNING always yields the row whether it was just inserted or already
// existed. Used by idempotent seeding so a retried seed can't raise 23505 and
// abort the transaction. The no-op update sets status to itself.
func (q *Queries) UpsertSkillVersion(ctx context.Context, arg UpsertSkillVersionParams) (AppSkillVersion, error) {
	row := q.db.QueryRow(ctx, upsertSkillVersion,
		arg.OrgID,
		arg.SkillID,
		arg.VersionNo,
		arg.Status,
		arg.ContentHash,
		arg.SizeBytes,
		arg.CreatedBy,
	)
	var i AppSkillVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SkillID,
		&i.VersionNo,
		&i.Status,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const writeAuditLog = `-- name: WriteAuditLog :one


INSERT INTO app.audit_log (
    org_id, actor_user, actor_token, action, target, metadata, ip, request_id, trace_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, org_id, actor_user, actor_token, action, target, metadata, ip, request_id, trace_id, created_at
`

type WriteAuditLogParams struct {
	OrgID      string
	ActorUser  *string
	ActorToken *string
	Action     string
	Target     pgtype.Text
	Metadata   []byte
	Ip         *netip.Addr
	RequestID  pgtype.Text
	TraceID    pgtype.Text
}

// NOTE: resolving a content host → owning site via the RLS-bypassing
// app.resolve_host() SECURITY DEFINER function (migration 0006) is done with raw
// pgx in the store (store.resolveHost), NOT sqlc: sqlc cannot infer column types
// from a RETURNS TABLE function (it emits interface{}). The store scans the known
// types directly. See services/api/internal/store/authz.go.
// ===========================================================================
// audit_log (Phase 4) — append-only record of sensitive actions
// ===========================================================================
// Append an audit row for a sensitive mutation. Runs inside the SAME RLS tenant
// tx as the action it records (org-scoped by the per-tx GUC + the explicit org_id),
// so an audit write can never land under the wrong tenant. actor_user is the verified
// user id (null for a deploy-token actor); actor_token is the deploy-token id when a
// token drove the action; metadata is freeform jsonb; ip/request_id/trace_id carry
// the request provenance.
func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) (AppAuditLog, error) {
	row := q.db.QueryRow(ctx, writeAuditLog,
		arg.OrgID,
		arg.ActorUser,
		arg.ActorToken,
		arg.Action,
		arg.Target,
		arg.Metadata,
		arg.Ip,
		arg.RequestID,
		arg.TraceID,
	)
	var i AppAuditLog
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ActorUser,
		&i.ActorToken,
		&i.Action,
		&i.Target,
		&i.Metadata,
		&i.Ip,
		&i.RequestID,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}
