// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Increment the org's running storage total by the new-blob delta (called once per
	// deploy with the sum of genuinely-new blob sizes).
	AddOrgStorage(ctx context.Context, arg AddOrgStorageParams) error
	// Claim a pending grant for the first verified account that matches it: set
	// claimed_at + claimed_by_user_id. Idempotent — re-claiming by the same user is a
	// no-op; we only set claim fields when still unclaimed so the original claimant
	// and timestamp are preserved.
	ClaimAllowlistEntry(ctx context.Context, arg ClaimAllowlistEntryParams) error
	// The number of sites in the active org (the per-ORG cap input, POOLED across all
	// members — seats are free, so the lever is org site count). Read under the
	// advisory lock above; RLS already scopes it to the active org and we filter by
	// org_id to be explicit.
	CountSitesForOrg(ctx context.Context, orgID string) (int64, error)
	// ===========================================================================
	// sites
	// ===========================================================================
	CreateSite(ctx context.Context, arg CreateSiteParams) (AppSite, error)
	CreateSiteVersion(ctx context.Context, arg CreateSiteVersionParams) (AppSiteVersion, error)
	DeleteAllowlistEntry(ctx context.Context, arg DeleteAllowlistEntryParams) error
	// Remove every external-email allowlist grant in the active org (reconcile on
	// disabling external sharing — revoke external access).
	DeleteExternalAllowlistEntriesForOrg(ctx context.Context) error
	DeleteHostRoute(ctx context.Context, host string) error
	// Drop a blob's ledger row when GC removes the orphaned R2 object; RETURNING the
	// size lets the caller decrement the running total. No row = it wasn't in the
	// ledger (e.g. uploaded before metering existed) → nothing to decrement.
	DeleteOrgBlob(ctx context.Context, arg DeleteOrgBlobParams) (int64, error)
	// SPDX-License-Identifier: FSL-1.1-Apache-2.0
	//
	// db/sqlc/query.sql
	//
	// Typed queries for the Go API's `app` schema. sqlc generates a method per
	// annotated query into services/api/internal/store/db. Every query here runs
	// inside a per-request transaction that has already executed the SET LOCAL
	// tenant GUCs (see internal/store + internal/middleware/rlstx), so RLS scopes
	// each statement to the active org. These queries therefore carry NO explicit
	// org filter beyond what RLS enforces, except where we deliberately re-derive a
	// resource's org for the confused-deputy guard (ARCHITECTURE.md §5).
	// ===========================================================================
	// org provisioning
	// ===========================================================================
	// Idempotent upsert of the app-side org anchor (PK = Better Auth organization.id).
	// ON CONFLICT DO NOTHING keeps a re-provision a no-op (the dashboard may call
	// ensure-org on every request).
	EnsureOrgMeta(ctx context.Context, id string) error
	// Idempotent upsert of the per-org counter row backing the quota gate.
	EnsureOrgUsage(ctx context.Context, orgID string) error
	// Look up a grant by (site, email) for the authz claim path.
	GetAllowlistEntryByEmail(ctx context.Context, arg GetAllowlistEntryByEmailParams) (AppAllowlistEntry, error)
	GetDomain(ctx context.Context, id string) (AppDomain, error)
	// Read the host's owning (org, site). Under the per-tx RLS tenant context this
	// returns a row ONLY if the active org owns the host; another org's row (or an
	// absent host) is a no-rows miss. Used by Publish / the projection writers to
	// assert the publishing site OWNS the host before writing route:<host>.
	GetHostRoute(ctx context.Context, host string) (AppHostRoute, error)
	GetOrgMeta(ctx context.Context, id string) (GetOrgMetaRow, error)
	// The org's current stored bytes (the storage cap-check input). 0 when the
	// org_usage row is somehow absent (fail-soft, like GetPlanTier).
	GetOrgStorage(ctx context.Context, orgID string) (int64, error)
	GetOrgUsage(ctx context.Context, orgID string) (GetOrgUsageRow, error)
	// The org's live entitlement tier (the authoritative cap-check input). In the
	// hosted build org_meta.plan_tier is synced from billing.subscriptions by the
	// Stripe webhook; in self-host it stays 'free' but the Unlimited provider ignores
	// it. Returns 'free' when the org row is somehow absent (fail-soft default).
	GetPlanTier(ctx context.Context, id string) (string, error)
	GetSite(ctx context.Context, id string) (AppSite, error)
	GetSiteAccessPolicy(ctx context.Context, siteID string) (AppSiteAccessPolicy, error)
	// LOGICAL storage of a single site = the byte size of its CURRENT (live) version
	// (site_versions.size_bytes, the sum of that version's file sizes). A site with no
	// live version is 0. "Logical" means NOT deduplicated across sites/versions: a file
	// shipped by two sites counts in both, the same per-folder model Dropbox/Drive use.
	// RLS scopes the read to the active org.
	GetSiteStorageBytes(ctx context.Context, id string) (int64, error)
	GetSiteVersion(ctx context.Context, id string) (AppSiteVersion, error)
	// Used to make a re-deploy of identical content idempotent (the per-site
	// content_hash unique constraint backs this).
	GetSiteVersionByContentHash(ctx context.Context, arg GetSiteVersionByContentHashParams) (AppSiteVersion, error)
	// Bump the org's sites_count counter, returning the new value. Run inside the
	// create-site tx after the row is inserted.
	IncSiteCount(ctx context.Context, orgID string) (int32, error)
	// ===========================================================================
	// domains (Phase 2) — Cloudflare-for-SaaS custom hostnames
	// ===========================================================================
	// Reserve a custom hostname for a site. hostname is GLOBALLY UNIQUE, so a
	// conflicting insert from any org raises 23505 (surfaced as ErrHostTaken). Stores
	// the Cloudflare custom-hostname id + the DCV record to surface to the user.
	InsertDomain(ctx context.Context, arg InsertDomainParams) (AppDomain, error)
	// ===========================================================================
	// host_routes (global host registry — the cross-tenant hijack guard)
	// ===========================================================================
	// Reserve a GLOBAL host for (org, site) inside the CreateSite tx. The PRIMARY KEY
	// on host means a host already owned by ANY org raises 23505 (unique_violation),
	// which the store surfaces as ErrHostTaken so the whole tx rolls back. RLS scopes
	// the row to the active org for later SELECT/UPDATE/DELETE, but the PK guard is
	// global regardless of RLS visibility.
	InsertHostRoute(ctx context.Context, arg InsertHostRouteParams) error
	// Record a content-addressed blob as stored for the org. Dedup-aware: ON CONFLICT
	// DO NOTHING means a blob already present for the org is NOT re-counted — RETURNING
	// yields a row (the size) ONLY when the blob is genuinely new, so the caller sums
	// the returned sizes as the storage delta. No row (pgx.ErrNoRows) = already stored.
	InsertOrgBlob(ctx context.Context, arg InsertOrgBlobParams) (int64, error)
	ListAllowlistEntries(ctx context.Context, siteID string) ([]AppAllowlistEntry, error)
	// Page the active org's audit log newest-first. RLS scopes the read to the org; the
	// (org_id, created_at DESC) index backs the order. Keyset-free LIMIT/OFFSET paging is
	// adequate for an admin audit viewer (small N per page).
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AppAuditLog, error)
	ListDomainsForSite(ctx context.Context, siteID string) ([]AppDomain, error)
	// Every host registered for a site in the GLOBAL registry — the canonical
	// <slug>.dropwaycontent.com host AND every verified custom-domain host. RLS
	// scopes the rows to the active org, so a caller only ever sees its own site's
	// hosts. An access-mode / policy change must rewrite EVERY one of these routes
	// (not just the canonical one), or a verified custom host keeps serving at the
	// OLD access_mode after the policy tightened (ARCHITECTURE.md §6 revocation).
	ListHostRoutesForSite(ctx context.Context, siteID string) ([]AppHostRoute, error)
	// Every site in the active org whose access_mode = 'public' (used by the reconcile
	// on disabling external sharing: these are downgraded to org_only).
	ListPublicSitesForOrg(ctx context.Context) ([]AppSite, error)
	// ===========================================================================
	// projection rebuild (the "KV is rebuildable from Postgres" invariant)
	// ===========================================================================
	// Every site that currently has a live version, joined to that version's
	// access_mode source (the site row). Drives projection.RebuildFromDB: Postgres
	// is authoritative, the KV/D1 projection is a rebuildable cache.
	ListPublishedSitesForRebuild(ctx context.Context) ([]ListPublishedSitesForRebuildRow, error)
	// LOGICAL storage per site for the active org (the current-version size of each
	// site, 0 when it has no live version) paired with the owning user, so the caller
	// can show per-site usage AND aggregate it per user. Same non-deduplicated model as
	// GetSiteStorageBytes. RLS scopes the read to the active org.
	ListSiteStorageForOrg(ctx context.Context) ([]ListSiteStorageForOrgRow, error)
	ListSiteVersions(ctx context.Context, siteID string) ([]AppSiteVersion, error)
	ListSites(ctx context.Context) ([]AppSite, error)
	// ===========================================================================
	// R2 version GC (Phase 4) — versions to retain per org
	// ===========================================================================
	// Every version of every site in the active org, newest first within each site,
	// flagged with whether it is the site's CURRENT (live) version. Drives the R2
	// version GC retention policy (keep current + last N): the GC groups by site, keeps
	// the current version + the top-N by version_no, reads those versions' manifests to
	// collect referenced blob shas, and deletes every org blob not in that set. RLS
	// scopes the rows to the active org. r2_prefix + id locate the manifest object.
	ListVersionsForGC(ctx context.Context) ([]ListVersionsForGCRow, error)
	// Serialize the members-cap preflight for an org: a transaction-scoped advisory
	// lock keyed by hashtext(org||':members'). Best-effort server-side enforcement on
	// OUR code path (Better Auth actually inserts the member row), so the lock just
	// makes our COUNT → policy check coherent under concurrent preflights.
	LockOrgMemberQuota(ctx context.Context, dollar_1 string) error
	// Serialize concurrent site creates for the SAME org: take a transaction-scoped
	// advisory lock keyed by hashtext(org||':sites'). Held until the create-site tx
	// commits/rolls back, it makes the COUNT → policy check → INSERT a critical
	// section, so two racing creates anywhere in the org can't both read current=N and
	// both insert (the TOCTOU the per-ORG cap must not allow). Advisory locks are
	// independent of RLS and of row locks, so this needs no rows to exist yet.
	LockOrgSiteQuota(ctx context.Context, dollar_1 string) error
	// ===========================================================================
	// storage metering (docs/pricing.md §5): org_blobs ledger + org_usage counter
	// ===========================================================================
	// Serialize concurrent deploys' storage accounting for an org: a transaction-scoped
	// advisory lock keyed by hashtext(org||':storage'), so the GetOrgStorage → cap check
	// → ledger INSERT → counter UPDATE is a critical section (the same TOCTOU guard the
	// site cap uses). Held until the deploy tx commits/rolls back.
	LockOrgStorageQuota(ctx context.Context, dollar_1 string) error
	// ===========================================================================
	// site_versions
	// ===========================================================================
	// The next monotonic version number for a site (1 on the first deploy).
	NextVersionNo(ctx context.Context, siteID string) (int32, error)
	// Reconcile the running total to the authoritative ledger sum (the cheap drift
	// fix; a deeper audit lists R2 to prune ledger rows orphaned by a crashed GC).
	RecomputeOrgStorage(ctx context.Context, orgID string) error
	// ===========================================================================
	// host resolution (Phase 2) — resolve a content host → owning site (for /authz)
	// ===========================================================================
	// Resolve a content host (the *.dropwaycontent.com label OR a verified custom
	// host) to its owning site via the global host registry, returning the site's
	// access fields. Runs under RLS so only the active org's hosts resolve — the
	// /authz mint sets the tenant from the resolved org first (see store.AuthzContext).
	ResolveSiteByHostRoute(ctx context.Context, host string) (ResolveSiteByHostRouteRow, error)
	// ===========================================================================
	// org policy (Phase 2) — allow_external_sharing toggle + reconcile
	// ===========================================================================
	// Toggle the org's external-sharing policy (admin/owner only, enforced in Go).
	SetAllowExternalSharing(ctx context.Context, arg SetAllowExternalSharingParams) error
	// Flip the live-version pointer (publish / rollback). RLS guarantees we can only
	// touch our own org's site; we also re-check the version belongs to the site.
	SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error
	// Toggle whether the Dropway MCP server may serve this org (admin/owner only,
	// enforced in Go). The MCP resource server ALSO re-checks org_meta.mcp_enabled per
	// request, so disabling takes effect immediately even for already-issued tokens.
	SetMcpEnabled(ctx context.Context, arg SetMcpEnabledParams) error
	// ===========================================================================
	// access policy (Phase 2) — per-site gating config
	// ===========================================================================
	// Flip a site's access_mode (the source for the edge RouteValue). RLS scopes the
	// UPDATE to the active org; the external-sharing trigger (0004) rejects 'public'
	// under a false org policy.
	SetSiteAccessMode(ctx context.Context, arg SetSiteAccessModeParams) error
	// Decrement the org's running storage total by the freed bytes (GC). GREATEST(0,…)
	// floors at zero so a reconciliation skew can never make the counter negative.
	SubOrgStorage(ctx context.Context, arg SubOrgStorageParams) error
	// Advance the custom-domain state machine (pending → verifying → verified/failed)
	// and the TLS status from a Cloudflare Status() poll.
	UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) (AppDomain, error)
	// ===========================================================================
	// allowlist (Phase 2)
	// ===========================================================================
	// Add (or re-add) an email grant to a site's allowlist. is_external marks an
	// email whose domain is not an org verified domain; the external-sharing trigger
	// (0004) rejects is_external=true under a false org policy. Re-adding an email
	// resets it to a fresh pending (unclaimed) grant.
	UpsertAllowlistEntry(ctx context.Context, arg UpsertAllowlistEntryParams) (AppAllowlistEntry, error)
	// ===========================================================================
	// host_routes (Phase 2) — register/unregister a custom host in the global registry
	// ===========================================================================
	// Register a host → (org, site) in the GLOBAL registry. Used when a custom domain
	// verifies (the content host is the custom hostname). PK on host enforces global
	// uniqueness; a conflict with another org raises 23505 (ErrHostTaken). ON CONFLICT
	// updates only when the row is already owned by THIS (org, site) — a different
	// owner can never be overwritten because RLS makes its row invisible to UPDATE, so
	// the ON CONFLICT target row isn't visible and the upsert raises instead.
	UpsertHostRoute(ctx context.Context, arg UpsertHostRouteParams) error
	// Insert or replace the per-site access policy (one row per site, PK = site_id).
	// password_hash is non-null only for mode='password'; expires_at / unlisted are
	// optional. The policy-mirror external-sharing trigger (0004) rejects mode='public'
	// under a false org policy.
	UpsertSiteAccessPolicy(ctx context.Context, arg UpsertSiteAccessPolicyParams) (AppSiteAccessPolicy, error)
	// NOTE: resolving a content host → owning site via the RLS-bypassing
	// app.resolve_host() SECURITY DEFINER function (migration 0006) is done with raw
	// pgx in the store (store.resolveHost), NOT sqlc: sqlc cannot infer column types
	// from a RETURNS TABLE function (it emits interface{}). The store scans the known
	// types directly. See services/api/internal/store/authz.go.
	// ===========================================================================
	// audit_log (Phase 4) — append-only record of sensitive actions
	// ===========================================================================
	// Append an audit row for a sensitive mutation. Runs inside the SAME RLS tenant
	// tx as the action it records (org-scoped by the per-tx GUC + the explicit org_id),
	// so an audit write can never land under the wrong tenant. actor_user is the verified
	// user id (null for a deploy-token actor); actor_token is the deploy-token id when a
	// token drove the action; metadata is freeform jsonb; ip/request_id/trace_id carry
	// the request provenance (ARCHITECTURE.md §10 / §2.3).
	WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) (AppAuditLog, error)
}

var _ Querier = (*Queries)(nil)
