// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createSite = `-- name: CreateSite :one

INSERT INTO app.sites (org_id, slug, owner_user_id, access_mode)
VALUES ($1, $2, $3, $4)
RETURNING id, org_id, slug, owner_user_id, access_mode, current_version_id, created_at
`

type CreateSiteParams struct {
	OrgID       string
	Slug        string
	OwnerUserID string
	AccessMode  string
}

// ===========================================================================
// sites
// ===========================================================================
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (AppSite, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.OrgID,
		arg.Slug,
		arg.OwnerUserID,
		arg.AccessMode,
	)
	var i AppSite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.OwnerUserID,
		&i.AccessMode,
		&i.CurrentVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createSiteVersion = `-- name: CreateSiteVersion :one
INSERT INTO app.site_versions (
    org_id, site_id, version_no, status, r2_prefix, content_hash, size_bytes, created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, site_id, version_no, status, r2_prefix, content_hash, size_bytes, created_by, created_at
`

type CreateSiteVersionParams struct {
	OrgID       string
	SiteID      string
	VersionNo   int32
	Status      string
	R2Prefix    string
	ContentHash string
	SizeBytes   int64
	CreatedBy   string
}

func (q *Queries) CreateSiteVersion(ctx context.Context, arg CreateSiteVersionParams) (AppSiteVersion, error) {
	row := q.db.QueryRow(ctx, createSiteVersion,
		arg.OrgID,
		arg.SiteID,
		arg.VersionNo,
		arg.Status,
		arg.R2Prefix,
		arg.ContentHash,
		arg.SizeBytes,
		arg.CreatedBy,
	)
	var i AppSiteVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.VersionNo,
		&i.Status,
		&i.R2Prefix,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const ensureOrgMeta = `-- name: EnsureOrgMeta :exec


INSERT INTO app.org_meta (id)
VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

// SPDX-License-Identifier: FSL-1.1-Apache-2.0
//
// db/sqlc/query.sql
//
// Typed queries for the Go API's `app` schema. sqlc generates a method per
// annotated query into services/api/internal/store/db. Every query here runs
// inside a per-request transaction that has already executed the SET LOCAL
// tenant GUCs (see internal/store + internal/middleware/rlstx), so RLS scopes
// each statement to the active org. These queries therefore carry NO explicit
// org filter beyond what RLS enforces, except where we deliberately re-derive a
// resource's org for the confused-deputy guard (ARCHITECTURE.md §5).
// ===========================================================================
// org provisioning
// ===========================================================================
// Idempotent upsert of the app-side org anchor (PK = Better Auth organization.id).
// ON CONFLICT DO NOTHING keeps a re-provision a no-op (the dashboard may call
// ensure-org on every request).
func (q *Queries) EnsureOrgMeta(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, ensureOrgMeta, id)
	return err
}

const ensureOrgUsage = `-- name: EnsureOrgUsage :exec
INSERT INTO app.org_usage (org_id)
VALUES ($1)
ON CONFLICT (org_id) DO NOTHING
`

// Idempotent upsert of the per-org counter row backing the quota gate.
func (q *Queries) EnsureOrgUsage(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, ensureOrgUsage, orgID)
	return err
}

const getHostRoute = `-- name: GetHostRoute :one
SELECT host, org_id, site_id, created_at
FROM app.host_routes
WHERE host = $1
`

// Read the host's owning (org, site). Under the per-tx RLS tenant context this
// returns a row ONLY if the active org owns the host; another org's row (or an
// absent host) is a no-rows miss. Used by Publish / the projection writers to
// assert the publishing site OWNS the host before writing route:<host>.
func (q *Queries) GetHostRoute(ctx context.Context, host string) (AppHostRoute, error) {
	row := q.db.QueryRow(ctx, getHostRoute, host)
	var i AppHostRoute
	err := row.Scan(
		&i.Host,
		&i.OrgID,
		&i.SiteID,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgMeta = `-- name: GetOrgMeta :one
SELECT id, plan_tier, allow_external_sharing, default_visibility, created_at
FROM app.org_meta
WHERE id = $1
`

func (q *Queries) GetOrgMeta(ctx context.Context, id string) (AppOrgMetum, error) {
	row := q.db.QueryRow(ctx, getOrgMeta, id)
	var i AppOrgMetum
	err := row.Scan(
		&i.ID,
		&i.PlanTier,
		&i.AllowExternalSharing,
		&i.DefaultVisibility,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgUsage = `-- name: GetOrgUsage :one
SELECT org_id, members_count, sites_count, updated_at
FROM app.org_usage
WHERE org_id = $1
`

func (q *Queries) GetOrgUsage(ctx context.Context, orgID string) (AppOrgUsage, error) {
	row := q.db.QueryRow(ctx, getOrgUsage, orgID)
	var i AppOrgUsage
	err := row.Scan(
		&i.OrgID,
		&i.MembersCount,
		&i.SitesCount,
		&i.UpdatedAt,
	)
	return i, err
}

const getSite = `-- name: GetSite :one
SELECT id, org_id, slug, owner_user_id, access_mode, current_version_id, created_at
FROM app.sites
WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id string) (AppSite, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i AppSite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.OwnerUserID,
		&i.AccessMode,
		&i.CurrentVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteVersion = `-- name: GetSiteVersion :one
SELECT id, org_id, site_id, version_no, status, r2_prefix, content_hash, size_bytes, created_by, created_at
FROM app.site_versions
WHERE id = $1
`

func (q *Queries) GetSiteVersion(ctx context.Context, id string) (AppSiteVersion, error) {
	row := q.db.QueryRow(ctx, getSiteVersion, id)
	var i AppSiteVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.VersionNo,
		&i.Status,
		&i.R2Prefix,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSiteVersionByContentHash = `-- name: GetSiteVersionByContentHash :one
SELECT id, org_id, site_id, version_no, status, r2_prefix, content_hash, size_bytes, created_by, created_at
FROM app.site_versions
WHERE site_id = $1 AND content_hash = $2
`

type GetSiteVersionByContentHashParams struct {
	SiteID      string
	ContentHash string
}

// Used to make a re-deploy of identical content idempotent (the per-site
// content_hash unique constraint backs this).
func (q *Queries) GetSiteVersionByContentHash(ctx context.Context, arg GetSiteVersionByContentHashParams) (AppSiteVersion, error) {
	row := q.db.QueryRow(ctx, getSiteVersionByContentHash, arg.SiteID, arg.ContentHash)
	var i AppSiteVersion
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.SiteID,
		&i.VersionNo,
		&i.Status,
		&i.R2Prefix,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const incSiteCount = `-- name: IncSiteCount :one
UPDATE app.org_usage
SET sites_count = sites_count + 1,
    updated_at  = now()
WHERE org_id = $1
RETURNING sites_count
`

// Bump the org's sites_count counter, returning the new value. Run inside the
// create-site tx after the row is inserted.
func (q *Queries) IncSiteCount(ctx context.Context, orgID string) (int32, error) {
	row := q.db.QueryRow(ctx, incSiteCount, orgID)
	var sites_count int32
	err := row.Scan(&sites_count)
	return sites_count, err
}

const insertHostRoute = `-- name: InsertHostRoute :exec

INSERT INTO app.host_routes (host, org_id, site_id)
VALUES ($1, $2, $3)
`

type InsertHostRouteParams struct {
	Host   string
	OrgID  string
	SiteID string
}

// ===========================================================================
// host_routes (global host registry — the cross-tenant hijack guard)
// ===========================================================================
// Reserve a GLOBAL host for (org, site) inside the CreateSite tx. The PRIMARY KEY
// on host means a host already owned by ANY org raises 23505 (unique_violation),
// which the store surfaces as ErrHostTaken so the whole tx rolls back. RLS scopes
// the row to the active org for later SELECT/UPDATE/DELETE, but the PK guard is
// global regardless of RLS visibility.
func (q *Queries) InsertHostRoute(ctx context.Context, arg InsertHostRouteParams) error {
	_, err := q.db.Exec(ctx, insertHostRoute, arg.Host, arg.OrgID, arg.SiteID)
	return err
}

const listPublishedSitesForRebuild = `-- name: ListPublishedSitesForRebuild :many

SELECT
    s.id            AS site_id,
    s.org_id        AS org_id,
    s.slug          AS slug,
    s.access_mode   AS access_mode,
    s.current_version_id AS version_id
FROM app.sites s
WHERE s.current_version_id IS NOT NULL
ORDER BY s.created_at
`

type ListPublishedSitesForRebuildRow struct {
	SiteID     string
	OrgID      string
	Slug       string
	AccessMode string
	VersionID  *string
}

// ===========================================================================
// projection rebuild (the "KV is rebuildable from Postgres" invariant)
// ===========================================================================
// Every site that currently has a live version, joined to that version's
// access_mode source (the site row). Drives projection.RebuildFromDB: Postgres
// is authoritative, the KV/D1 projection is a rebuildable cache.
func (q *Queries) ListPublishedSitesForRebuild(ctx context.Context) ([]ListPublishedSitesForRebuildRow, error) {
	rows, err := q.db.Query(ctx, listPublishedSitesForRebuild)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedSitesForRebuildRow{}
	for rows.Next() {
		var i ListPublishedSitesForRebuildRow
		if err := rows.Scan(
			&i.SiteID,
			&i.OrgID,
			&i.Slug,
			&i.AccessMode,
			&i.VersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSiteVersions = `-- name: ListSiteVersions :many
SELECT id, org_id, site_id, version_no, status, r2_prefix, content_hash, size_bytes, created_by, created_at
FROM app.site_versions
WHERE site_id = $1
ORDER BY version_no DESC
`

func (q *Queries) ListSiteVersions(ctx context.Context, siteID string) ([]AppSiteVersion, error) {
	rows, err := q.db.Query(ctx, listSiteVersions, siteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSiteVersion{}
	for rows.Next() {
		var i AppSiteVersion
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.SiteID,
			&i.VersionNo,
			&i.Status,
			&i.R2Prefix,
			&i.ContentHash,
			&i.SizeBytes,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSites = `-- name: ListSites :many
SELECT id, org_id, slug, owner_user_id, access_mode, current_version_id, created_at
FROM app.sites
ORDER BY created_at DESC
`

func (q *Queries) ListSites(ctx context.Context) ([]AppSite, error) {
	rows, err := q.db.Query(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSite{}
	for rows.Next() {
		var i AppSite
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.OwnerUserID,
			&i.AccessMode,
			&i.CurrentVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextVersionNo = `-- name: NextVersionNo :one

SELECT COALESCE(MAX(version_no), 0) + 1 AS next_version_no
FROM app.site_versions
WHERE site_id = $1
`

// ===========================================================================
// site_versions
// ===========================================================================
// The next monotonic version number for a site (1 on the first deploy).
func (q *Queries) NextVersionNo(ctx context.Context, siteID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextVersionNo, siteID)
	var next_version_no int32
	err := row.Scan(&next_version_no)
	return next_version_no, err
}

const setCurrentVersion = `-- name: SetCurrentVersion :exec
UPDATE app.sites
SET current_version_id = $2
WHERE id = $1
`

type SetCurrentVersionParams struct {
	ID               string
	CurrentVersionID *string
}

// Flip the live-version pointer (publish / rollback). RLS guarantees we can only
// touch our own org's site; we also re-check the version belongs to the site.
func (q *Queries) SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error {
	_, err := q.db.Exec(ctx, setCurrentVersion, arg.ID, arg.CurrentVersionID)
	return err
}
