// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Increment the org's running storage total by the new-blob delta (called once per
	// deploy with the sum of genuinely-new blob sizes).
	AddOrgStorage(ctx context.Context, arg AddOrgStorageParams) error
	// Reserve $2 consecutive seq numbers; returns the FIRST reserved number. seq
	// stays monotonic across pruning because the allocator never rewinds.
	AllocateChatSeq(ctx context.Context, arg AllocateChatSeqParams) (int32, error)
	// Transcript append with a per-session monotonic seq (MAX+1 over an empty set
	// yields 1). Two racing appends can collide on the (session_id, seq) unique
	// key; the store retries — in practice a session has a single writer (the turn
	// loop holds the session lock).
	AppendAIMessage(ctx context.Context, arg AppendAIMessageParams) (AppAiMessage, error)
	// Claim a pending grant for the first verified account that matches it: set
	// claimed_at + claimed_by_user_id. Idempotent — re-claiming by the same user is a
	// no-op; we only set claim fields when still unclaimed so the original claimant
	// and timestamp are preserved.
	ClaimAllowlistEntry(ctx context.Context, arg ClaimAllowlistEntryParams) error
	// Active = a session a user could still be driving (not archived/failed).
	CountActiveAISessions(ctx context.Context, orgID string) (int64, error)
	CountChatLogsForOrg(ctx context.Context, orgID string) (int64, error)
	CountChatMessages(ctx context.Context, chatLogID string) (int64, error)
	CountFolderItems(ctx context.Context, folderID string) (int64, error)
	// The number of sites in the active org (the per-ORG cap input, POOLED across all
	// members — seats are free, so the lever is org site count). Read under the
	// advisory lock above; RLS already scopes it to the active org and we filter by
	// org_id to be explicit.
	CountSitesForOrg(ctx context.Context, orgID string) (int64, error)
	CountSkillsForOrg(ctx context.Context, orgID string) (int64, error)
	// ===========================================================================
	// AI builder — sessions, transcript, cost ledger
	// ===========================================================================
	CreateAISession(ctx context.Context, arg CreateAISessionParams) (AppAiSession, error)
	CreateChatLog(ctx context.Context, arg CreateChatLogParams) (AppChatLog, error)
	// ===========================================================================
	// site_comments — org-internal discussion on a shared site, with @mentions
	// ===========================================================================
	// Add a comment to a feed post (site or skill). mentioned_user_ids is the set of
	// tagged org users (identity ids). RLS scopes the INSERT to the active org (the
	// WITH CHECK clause on the tenant policy rejects a row whose org_id isn't the
	// active tenant).
	CreatePostComment(ctx context.Context, arg CreatePostCommentParams) (AppPostComment, error)
	// Insert a preset seed skill, or DO NOTHING if the org already has that slug
	// (a real user's skill, or this seed from a prior attempt). ON CONFLICT means a
	// collision never raises 23505 and aborts the seeding transaction; a no-rows
	// result tells the caller to inspect the existing row and skip it unless it is
	// our own seed.
	CreateSeedSkill(ctx context.Context, arg CreateSeedSkillParams) (AppSkill, error)
	// ===========================================================================
	// sites
	// ===========================================================================
	CreateSite(ctx context.Context, arg CreateSiteParams) (AppSite, error)
	CreateSiteVersion(ctx context.Context, arg CreateSiteVersionParams) (AppSiteVersion, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (AppSkill, error)
	// ===========================================================================
	// skill folders — admin-curated taxonomy + preset flags
	// ===========================================================================
	CreateSkillFolder(ctx context.Context, arg CreateSkillFolderParams) (AppSkillFolder, error)
	CreateSkillVersion(ctx context.Context, arg CreateSkillVersionParams) (AppSkillVersion, error)
	DeleteAISession(ctx context.Context, id string) error
	DeleteAllowlistEntry(ctx context.Context, arg DeleteAllowlistEntryParams) error
	DeleteChatLog(ctx context.Context, id string) (int64, error)
	DeleteChatMessage(ctx context.Context, arg DeleteChatMessageParams) (int64, error)
	// Remove a custom domain, returning its hostname + cf_hostname_id so the caller can
	// also drop the global host route (so serve/edge stop resolving the host) and delete
	// the Cloudflare custom hostname. RLS scopes the delete to the active org.
	DeleteDomain(ctx context.Context, id string) (DeleteDomainRow, error)
	// Ops sweep: purge preview rows whose deadline passed more than the supplied
	// grace interval ago, returning hosts for KV cleanup. The edge already 410s
	// them; this is bookkeeping, not enforcement.
	DeleteExpiredPreviewRoutes(ctx context.Context, expiresAt pgtype.Timestamptz) ([]string, error)
	// Remove every external-email allowlist grant in the active org (reconcile on
	// disabling external sharing — revoke external access).
	DeleteExternalAllowlistEntriesForOrg(ctx context.Context) error
	DeleteHostRoute(ctx context.Context, host string) error
	// Drop a blob's ledger row when GC removes the orphaned R2 object; RETURNING the
	// size lets the caller decrement the running total. No row = it wasn't in the
	// ledger (e.g. uploaded before metering existed) → nothing to decrement.
	DeleteOrgBlob(ctx context.Context, arg DeleteOrgBlobParams) (int64, error)
	// Drop every comment on a subject (called on the subject's delete; see above).
	DeletePostCommentsForSubject(ctx context.Context, arg DeletePostCommentsForSubjectParams) error
	// Remove the caller's vote on a feed post (un-vote). RLS scopes the delete to the org.
	DeletePostVote(ctx context.Context, arg DeletePostVoteParams) error
	// Drop every vote on a subject (called when the site/skill itself is deleted,
	// since the polymorphic table can't FK-cascade to two parents).
	DeletePostVotesForSubject(ctx context.Context, arg DeletePostVotesForSubjectParams) error
	// Drop a version's preview routes, returning the hosts so the caller can also
	// delete the KV keys (publish and explicit preview deletion).
	DeletePreviewRoutesForVersion(ctx context.Context, versionID *string) ([]string, error)
	// Drop a site's preview routes except the one pinning keep_version_id, returning
	// the removed hosts for KV cleanup. Keeps at most one live preview per site: a new
	// AI draft removes the earlier drafts' previews (pass the new version to keep).
	// Pass NULL for keep_version_id to remove ALL of the site's previews (publish).
	DeleteSitePreviewRoutesExcept(ctx context.Context, arg DeleteSitePreviewRoutesExceptParams) ([]string, error)
	// Remove a skill (versions + folder memberships cascade). RETURNING detects an
	// RLS-invisible / absent row as a no-rows miss (→ ErrNotFound).
	DeleteSkill(ctx context.Context, id string) (string, error)
	// Memberships cascade; the skills themselves survive.
	DeleteSkillFolder(ctx context.Context, id string) (string, error)
	// Replace-memberships helper: clear a skill's memberships before re-inserting
	// the new set (PUT /skills/{id}/folders semantics), preserving nothing.
	DeleteSkillFolderItemsForSkill(ctx context.Context, skillID string) error
	// SPDX-License-Identifier: FSL-1.1-Apache-2.0
	//
	// db/sqlc/query.sql
	//
	// Typed queries for the Go API's `app` schema. sqlc generates a method per
	// annotated query into services/api/internal/store/db. Every query here runs
	// inside a per-request transaction that has already executed the SET LOCAL
	// tenant GUCs (see internal/store + internal/middleware/rlstx), so RLS scopes
	// each statement to the active org. These queries therefore carry NO explicit
	// org filter beyond what RLS enforces, except where we deliberately re-derive a
	// resource's org for the confused-deputy guard.
	// ===========================================================================
	// org provisioning
	// ===========================================================================
	// Idempotent upsert of the app-side org anchor (PK = Better Auth organization.id).
	// ON CONFLICT DO NOTHING keeps a re-provision a no-op (the dashboard may call
	// ensure-org on every request).
	EnsureOrgMeta(ctx context.Context, id string) error
	// Idempotent upsert of the per-org counter row backing the quota gate.
	EnsureOrgUsage(ctx context.Context, orgID string) error
	GetAISession(ctx context.Context, id string) (AppAiSession, error)
	// Look up a grant by (site, email) for the authz claim path.
	GetAllowlistEntryByEmail(ctx context.Context, arg GetAllowlistEntryByEmailParams) (AppAllowlistEntry, error)
	GetChatLog(ctx context.Context, id string) (AppChatLog, error)
	GetChatLogBySite(ctx context.Context, siteID *string) (AppChatLog, error)
	// The org chat-log kill switch; fail-soft true (like GetPlanTier's default).
	GetChatLogsEnabled(ctx context.Context, id string) (bool, error)
	GetDomain(ctx context.Context, id string) (AppDomain, error)
	// Read the host's owning (org, site). Under the per-tx RLS tenant context this
	// returns a row ONLY if the active org owns the host; another org's row (or an
	// absent host) is a no-rows miss. Used by Publish / the projection writers to
	// assert the publishing site OWNS the host before writing route:<host>.
	GetHostRoute(ctx context.Context, host string) (AppHostRoute, error)
	// Get-or-create a folder by (org_id, slug): a no-op DO UPDATE so RETURNING
	// always yields the row. Used by idempotent seeding so re-running against an
	// org that already has a default folder (e.g. an admin created it first) never
	// raises 23505 and aborts the seed transaction.
	GetOrCreateSkillFolder(ctx context.Context, arg GetOrCreateSkillFolderParams) (AppSkillFolder, error)
	GetOrgMeta(ctx context.Context, id string) (GetOrgMetaRow, error)
	GetOrgSkillsSeeded(ctx context.Context, id string) (bool, error)
	// The org's current stored bytes (the storage cap-check input). 0 when the
	// org_usage row is somehow absent (fail-soft, like GetPlanTier).
	GetOrgStorage(ctx context.Context, orgID string) (int64, error)
	GetOrgUsage(ctx context.Context, orgID string) (GetOrgUsageRow, error)
	// The org's live entitlement tier (the authoritative cap-check input). In the
	// hosted build org_meta.plan_tier is synced from billing.subscriptions by the
	// Stripe webhook; in self-host it stays 'free' but the Unlimited provider ignores
	// it. Returns 'free' when the org row is somehow absent (fail-soft default).
	GetPlanTier(ctx context.Context, id string) (string, error)
	// A feed post's net vote score (sum of +1/-1). RLS scopes the read to the org.
	GetPostVoteScore(ctx context.Context, arg GetPostVoteScoreParams) (int64, error)
	GetSite(ctx context.Context, id string) (AppSite, error)
	GetSiteAccessPolicy(ctx context.Context, siteID string) (AppSiteAccessPolicy, error)
	// The version stamp for an append while attached (NULL before first publish).
	GetSiteCurrentVersionID(ctx context.Context, id string) (*string, error)
	// LOGICAL storage of a single site = the byte size of its CURRENT (live) version
	// (site_versions.size_bytes, the sum of that version's file sizes). A site with no
	// live version is 0. "Logical" means NOT deduplicated across sites/versions: a file
	// shipped by two sites counts in both, the same per-folder model Dropbox/Drive use.
	// RLS scopes the read to the active org.
	GetSiteStorageBytes(ctx context.Context, id string) (int64, error)
	GetSiteVersion(ctx context.Context, id string) (AppSiteVersion, error)
	// Used to make a re-deploy of identical content idempotent (the per-site
	// content_hash unique constraint backs this).
	GetSiteVersionByContentHash(ctx context.Context, arg GetSiteVersionByContentHashParams) (AppSiteVersion, error)
	// Embeds the full skill row plus its current version's size (0 when unset), so
	// reads never N+1 a per-skill version lookup.
	GetSkill(ctx context.Context, id string) (GetSkillRow, error)
	GetSkillBySlug(ctx context.Context, slug string) (GetSkillBySlugRow, error)
	GetSkillFolder(ctx context.Context, id string) (AppSkillFolder, error)
	GetSkillFolderBySlug(ctx context.Context, slug string) (AppSkillFolder, error)
	GetSkillVersion(ctx context.Context, id string) (AppSkillVersion, error)
	// Idempotent re-upload of identical content (the per-skill content_hash unique
	// constraint backs this).
	GetSkillVersionByContentHash(ctx context.Context, arg GetSkillVersionByContentHashParams) (AppSkillVersion, error)
	// Bump the org's sites_count counter, returning the new value. Run inside the
	// create-site tx after the row is inserted.
	IncSiteCount(ctx context.Context, orgID string) (int32, error)
	// Append one OpenRouter generation to the cost ledger. Idempotent on the
	// generation id (a retried turn never double-counts); RETURNING yields a row
	// only when the generation is genuinely new (pgx.ErrNoRows = already recorded),
	// mirroring InsertOrgBlob's dedup contract.
	InsertAIUsage(ctx context.Context, arg InsertAIUsageParams) (AppAiUsage, error)
	InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (AppChatMessage, error)
	// ===========================================================================
	// domains (Phase 2) — Cloudflare-for-SaaS custom hostnames
	// ===========================================================================
	// Reserve a custom hostname for a site. hostname is GLOBALLY UNIQUE, so a
	// conflicting insert from any org raises 23505 (surfaced as ErrHostTaken). Stores
	// the Cloudflare custom-hostname id + the DCV record to surface to the user.
	InsertDomain(ctx context.Context, arg InsertDomainParams) (AppDomain, error)
	// ===========================================================================
	// host_routes (global host registry — the cross-tenant hijack guard)
	// ===========================================================================
	// Reserve a GLOBAL host for (org, site) inside the CreateSite tx. The PRIMARY KEY
	// on host means a host already owned by ANY org raises 23505 (unique_violation),
	// which the store surfaces as ErrHostTaken so the whole tx rolls back. RLS scopes
	// the row to the active org for later SELECT/UPDATE/DELETE, but the PK guard is
	// global regardless of RLS visibility.
	InsertHostRoute(ctx context.Context, arg InsertHostRouteParams) error
	// Record a content-addressed blob as stored for the org. Dedup-aware: ON CONFLICT
	// DO NOTHING means a blob already present for the org is NOT re-counted — RETURNING
	// yields a row (the size) ONLY when the blob is genuinely new, so the caller sums
	// the returned sizes as the storage delta. No row (pgx.ErrNoRows) = already stored.
	InsertOrgBlob(ctx context.Context, arg InsertOrgBlobParams) (int64, error)
	// The transcript in order, optionally resuming after a seq (SSE Last-Event-ID;
	// pass 0 for the full history).
	ListAIMessages(ctx context.Context, arg ListAIMessagesParams) ([]AppAiMessage, error)
	ListAISessionsForOrg(ctx context.Context, orgID string) ([]AppAiSession, error)
	ListAISessionsForSite(ctx context.Context, siteID string) ([]AppAiSession, error)
	// Recent ledger rows for the billing page's usage detail.
	ListAIUsageForOrg(ctx context.Context, arg ListAIUsageForOrgParams) ([]AppAiUsage, error)
	ListAllowlistEntries(ctx context.Context, siteID string) ([]AppAllowlistEntry, error)
	// Page the active org's audit log newest-first. RLS scopes the read to the org; the
	// (org_id, created_at DESC) index backs the order. Keyset-free LIMIT/OFFSET paging is
	// adequate for an admin audit viewer (small N per page).
	ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AppAuditLog, error)
	// The org's chat library, newest first, with a live message count per log.
	ListChatLogs(ctx context.Context, orgID string) ([]ListChatLogsRow, error)
	// Ascending seq page: seq > $2, LIMIT $3 (the panel and API both page forward).
	ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]AppChatMessage, error)
	// ===========================================================================
	// skills seeding — lazy per-org default folders + preset skills
	// ===========================================================================
	// Every skill's CURRENT version (latest-only model: that is the only version
	// whose blobs must survive GC — superseded skill versions' blobs become
	// orphans). The R2 GC unions these manifests' blob refs with the retained site
	// versions' refs before deleting unreferenced org blobs; without this, skill
	// content would look orphaned to a site-only GC and be deleted. RLS scopes the
	// rows to the active org.
	ListCurrentSkillVersionsForGC(ctx context.Context) ([]ListCurrentSkillVersionsForGCRow, error)
	ListDomainsForSite(ctx context.Context, siteID string) ([]AppDomain, error)
	// The org feed's SITE posts: every site in the active org that is feed-visible
	// (not private), newest first (older sites sink to the bottom). Each row carries
	// its net vote score, the CALLER's own vote ($1 = caller user id; 0 when they
	// haven't voted), and its comment count, so the feed renders the up/down controls
	// + counts in one query (no N+1). Votes/comments are polymorphic (subject_type =
	// 'site'). RLS scopes every read to the active org.
	ListFeedSites(ctx context.Context, userID string) ([]ListFeedSitesRow, error)
	// The org feed's SKILL posts: every skill in the active org that is feed-visible,
	// newest first, each carrying its current-version size, net vote score, the
	// caller's own vote ($1), and its comment count (subject_type = 'skill'). Skills
	// that never finalized an upload (no current version) are shown only to their
	// owner, so half-finished uploads don't clutter the feed. RLS scopes every read.
	ListFeedSkills(ctx context.Context, userID string) ([]ListFeedSkillsRow, error)
	// Every skill in a folder that has a live version (the bulk-download set).
	ListFolderSkills(ctx context.Context, folderID string) ([]ListFolderSkillsRow, error)
	// Folder memberships for a set of skills in one round-trip (the folder chips on
	// each row of a skills listing — no N+1).
	ListFoldersForSkills(ctx context.Context, skillIds []string) ([]ListFoldersForSkillsRow, error)
	// Every host registered for a site in the GLOBAL registry — the canonical
	// <slug>.dropwaycontent.com host AND every verified custom-domain host. RLS
	// scopes the rows to the active org, so a caller only ever sees its own site's
	// hosts. An access-mode / policy change must rewrite EVERY one of these routes
	// (not just the canonical one), or a verified custom host keeps serving at the
	// OLD access_mode after the policy tightened (revocation).
	ListHostRoutesForSite(ctx context.Context, siteID string) ([]AppHostRoute, error)
	// A feed post's comment thread, displayed oldest-first (top-to-bottom like a
	// conversation) but BOUNDED to the most recent $3 comments so a long thread can't
	// load an unbounded result. RLS scopes the read to the active org; the
	// (subject_type, subject_id, created_at) index backs both orderings.
	ListPostComments(ctx context.Context, arg ListPostCommentsParams) ([]AppPostComment, error)
	// Unexpired preview routes joined to their site's access fields, for the DR
	// rebuild: previews are part of the "KV is rebuildable from Postgres"
	// invariant. Expired rows are skipped (the edge would 410 them anyway).
	ListPreviewRoutesForRebuild(ctx context.Context) ([]ListPreviewRoutesForRebuildRow, error)
	ListPreviewRoutesForVersion(ctx context.Context, versionID *string) ([]AppHostRoute, error)
	// Every site in the active org whose access_mode = 'public' (used by the reconcile
	// on disabling external sharing: these are downgraded to org_only).
	ListPublicSitesForOrg(ctx context.Context) ([]AppSite, error)
	// ===========================================================================
	// projection rebuild (the "KV is rebuildable from Postgres" invariant)
	// ===========================================================================
	// Every site that currently has a live version, joined to that version's
	// access_mode source (the site row). Drives projection.RebuildFromDB: Postgres
	// is authoritative, the KV/D1 projection is a rebuildable cache.
	ListPublishedSitesForRebuild(ctx context.Context) ([]ListPublishedSitesForRebuildRow, error)
	// LOGICAL storage per site for the active org (the current-version size of each
	// site, 0 when it has no live version) paired with the owning user, so the caller
	// can show per-site usage AND aggregate it per user. Same non-deduplicated model as
	// GetSiteStorageBytes. RLS scopes the read to the active org.
	ListSiteStorageForOrg(ctx context.Context) ([]ListSiteStorageForOrgRow, error)
	ListSiteVersions(ctx context.Context, siteID string) ([]AppSiteVersion, error)
	ListSites(ctx context.Context) ([]AppSite, error)
	// The org's folders with their member counts (the folder tabs + admin panel).
	ListSkillFolders(ctx context.Context) ([]ListSkillFoldersRow, error)
	// Search + filter the active org's skills. q matches slug/title/description
	// (ILIKE, '' = no text filter); folder_slug restricts to members of that folder
	// ('' = any); presets_only additionally requires the membership's is_preset flag.
	// Skills that have never finalized an upload (no current version) are visible
	// only to their owner (caller_id), so half-finished uploads don't clutter the
	// org listing. RLS scopes every read to the active org.
	ListSkills(ctx context.Context, arg ListSkillsParams) ([]ListSkillsRow, error)
	// Ledger rows the cloud meter has not acked yet (reported_to_billing_at IS
	// NULL), oldest first, for the per-row meter send + the ops retry sweep.
	ListUnreportedAIUsage(ctx context.Context, arg ListUnreportedAIUsageParams) ([]AppAiUsage, error)
	// ===========================================================================
	// R2 version GC (Phase 4) — versions to retain per org
	// ===========================================================================
	// Every version of every site in the active org, newest first within each site,
	// flagged with whether it is the site's CURRENT (live) version. Drives the R2
	// version GC retention policy (keep current + last N): the GC groups by site, keeps
	// the current version + the top-N by version_no, reads those versions' manifests to
	// collect referenced blob shas, and deletes every org blob not in that set. RLS
	// scopes the rows to the active org. r2_prefix + id locate the manifest object.
	ListVersionsForGC(ctx context.Context) ([]ListVersionsForGCRow, error)
	// Serialize appends/prunes/deletes on ONE log: the append tx holds this across
	// COUNT → policy (hard cap) or INSERT → prune (window), so two concurrent
	// appends can't both slip past the cap or over-prune.
	LockChatLogAppend(ctx context.Context, dollar_1 string) error
	// Serialize concurrent session creates for the SAME org (TOCTOU guard for the
	// per-org active-session concurrency cap, same pattern as LockOrgSiteQuota).
	LockOrgAISessionQuota(ctx context.Context, dollar_1 string) error
	// ===========================================================================
	// chat logs (Share This Session) — append-only conversation histories with
	// optional site attachment (migration 0013)
	// ===========================================================================
	// Serialize concurrent chat-log creates for the SAME org (the same COUNT →
	// policy → INSERT critical section the site/skill caps use).
	LockOrgChatLogQuota(ctx context.Context, dollar_1 string) error
	// Serialize the members-cap preflight for an org: a transaction-scoped advisory
	// lock keyed by hashtext(org||':members'). Best-effort server-side enforcement on
	// OUR code path (Better Auth actually inserts the member row), so the lock just
	// makes our COUNT → policy check coherent under concurrent preflights.
	LockOrgMemberQuota(ctx context.Context, dollar_1 string) error
	// Serialize concurrent site creates for the SAME org: take a transaction-scoped
	// advisory lock keyed by hashtext(org||':sites'). Held until the create-site tx
	// commits/rolls back, it makes the COUNT → policy check → INSERT a critical
	// section, so two racing creates anywhere in the org can't both read current=N and
	// both insert (the TOCTOU the per-ORG cap must not allow). Advisory locks are
	// independent of RLS and of row locks, so this needs no rows to exist yet.
	LockOrgSiteQuota(ctx context.Context, dollar_1 string) error
	// ===========================================================================
	// skills (migration 0008) — org-wide skill sharing
	// ===========================================================================
	// Serialize concurrent skill creates for the SAME org (the same COUNT → policy →
	// INSERT critical section the site cap uses).
	LockOrgSkillQuota(ctx context.Context, dollar_1 string) error
	// Serialize concurrent first-touches of the skills feature for an org, so the
	// skills_seeded check → seed → set-flag sequence runs exactly once.
	LockOrgSkillsSeed(ctx context.Context, dollar_1 string) error
	// ===========================================================================
	// storage metering: org_blobs ledger + org_usage counter
	// ===========================================================================
	// Serialize concurrent deploys' storage accounting for an org: a transaction-scoped
	// advisory lock keyed by hashtext(org||':storage'), so the GetOrgStorage → cap check
	// → ledger INSERT → counter UPDATE is a critical section (the same TOCTOU guard the
	// site cap uses). Held until the deploy tx commits/rolls back.
	LockOrgStorageQuota(ctx context.Context, dollar_1 string) error
	// Serialize concurrent membership inserts for the SAME folder, so the COUNT →
	// per-folder cap check → INSERT is a critical section (free tier caps skills per
	// folder; see quota.ResourceSkillPerFolder).
	LockSkillFolderQuota(ctx context.Context, dollar_1 string) error
	MarkAIUsageReported(ctx context.Context, id string) error
	NextSkillVersionNo(ctx context.Context, skillID string) (int32, error)
	// ===========================================================================
	// site_versions
	// ===========================================================================
	// The next monotonic version number for a site (1 on the first deploy).
	NextVersionNo(ctx context.Context, siteID string) (int32, error)
	// Free-tier rolling window: keep the NEWEST $2 rows of the log, delete the
	// rest. Runs under LockChatLogAppend in the same tx as the INSERT.
	PruneChatMessages(ctx context.Context, arg PruneChatMessagesParams) (int64, error)
	// Reconcile the running total to the authoritative ledger sum (the cheap drift
	// fix; a deeper audit lists R2 to prune ledger rows orphaned by a crashed GC).
	RecomputeOrgStorage(ctx context.Context, orgID string) error
	RemoveSkillFolderItem(ctx context.Context, arg RemoveSkillFolderItemParams) (string, error)
	RenameSkillFolder(ctx context.Context, arg RenameSkillFolderParams) (AppSkillFolder, error)
	// ===========================================================================
	// host resolution (Phase 2) — resolve a content host → owning site (for /authz)
	// ===========================================================================
	// Resolve a content host (the *.dropwaycontent.com label OR a verified custom
	// host) to its owning site via the global host registry, returning the site's
	// access fields. Runs under RLS so only the active org's hosts resolve — the
	// /authz mint sets the tenant from the resolved org first (see store.AuthzContext).
	ResolveSiteByHostRoute(ctx context.Context, host string) (ResolveSiteByHostRouteRow, error)
	// Org-level AI builder kill switch (owner/admin only, enforced in Go), the
	// exact analog of SetMcpEnabled.
	SetAIEnabled(ctx context.Context, arg SetAIEnabledParams) error
	SetAIMonthlyCap(ctx context.Context, arg SetAIMonthlyCapParams) error
	SetAISessionLatestVersion(ctx context.Context, arg SetAISessionLatestVersionParams) error
	// Cache the live sandbox handle (NULLs clear it after a reap/destroy).
	SetAISessionSandbox(ctx context.Context, arg SetAISessionSandboxParams) error
	SetAISessionStatus(ctx context.Context, arg SetAISessionStatusParams) error
	// ===========================================================================
	// org policy (Phase 2) — allow_external_sharing toggle + reconcile
	// ===========================================================================
	// Toggle the org's external-sharing policy (admin/owner only, enforced in Go).
	SetAllowExternalSharing(ctx context.Context, arg SetAllowExternalSharingParams) error
	SetChatLogAllowMemberEdits(ctx context.Context, arg SetChatLogAllowMemberEditsParams) (AppChatLog, error)
	SetChatLogPanelEnabled(ctx context.Context, arg SetChatLogPanelEnabledParams) (AppChatLog, error)
	// Attach ($2 = site id), detach ($2 = NULL), or move a log. The partial unique
	// index chat_logs_site_key rejects attaching to a site that already has one.
	SetChatLogSite(ctx context.Context, arg SetChatLogSiteParams) (AppChatLog, error)
	SetChatLogsEnabled(ctx context.Context, arg SetChatLogsEnabledParams) error
	// Flip the live-version pointer (publish / rollback). RLS guarantees we can only
	// touch our own org's site; we also re-check the version belongs to the site.
	SetCurrentVersion(ctx context.Context, arg SetCurrentVersionParams) error
	// Toggle whether the Dropway MCP server may serve this org (admin/owner only,
	// enforced in Go). The MCP resource server ALSO re-checks org_meta.mcp_enabled per
	// request, so disabling takes effect immediately even for already-issued tokens.
	SetMcpEnabled(ctx context.Context, arg SetMcpEnabledParams) error
	SetOrgSkillsSeeded(ctx context.Context, arg SetOrgSkillsSeededParams) error
	// ===========================================================================
	// access policy (Phase 2) — per-site gating config
	// ===========================================================================
	// Flip a site's access_mode (the source for the edge RouteValue). RLS scopes the
	// UPDATE to the active org; the external-sharing trigger (0004) rejects 'public'
	// under a false org policy.
	SetSiteAccessMode(ctx context.Context, arg SetSiteAccessModeParams) error
	// ===========================================================================
	// collaboration toggles (migration 0014): "allow non-creators to modify"
	// ===========================================================================
	SetSiteAllowMemberEdits(ctx context.Context, arg SetSiteAllowMemberEditsParams) (AppSite, error)
	// Set a site's human feed metadata (title + description). Empty strings are passed
	// as NULL by the caller so "clear it" round-trips to a null column. RLS scopes the
	// UPDATE to the active org; the handler restricts it to the owner or an org admin.
	SetSiteFeedMeta(ctx context.Context, arg SetSiteFeedMetaParams) (AppSite, error)
	// Mark a site shared-to-feed (true) or private/off-feed (false). RLS scopes the
	// UPDATE to the active org; the handler additionally restricts it to the site's
	// owner or an org admin/owner. Does NOT touch access_mode, so the edge projection
	// is unaffected (feed visibility is the discovery axis, not the access axis).
	SetSiteFeedVisible(ctx context.Context, arg SetSiteFeedVisibleParams) (AppSite, error)
	SetSkillAllowMemberEdits(ctx context.Context, arg SetSkillAllowMemberEditsParams) (AppSkill, error)
	// Flip the live pointer (finalize = publish in the latest-only v1 model).
	SetSkillCurrentVersion(ctx context.Context, arg SetSkillCurrentVersionParams) error
	// Share a skill to the org feed (true) or make it private/off-feed (false). RLS
	// scopes the UPDATE to the active org; the handler restricts it to the skill's
	// owner or an org admin/owner. A miss surfaces as a no-rows error (→ ErrNotFound).
	SetSkillFeedVisible(ctx context.Context, arg SetSkillFeedVisibleParams) (AppSkill, error)
	SetSkillFolderItemPreset(ctx context.Context, arg SetSkillFolderItemPresetParams) (SetSkillFolderItemPresetRow, error)
	// Fill a skill's human metadata (from SKILL.md frontmatter on finalize, or an
	// explicit edit). Empty strings are passed as NULL so "unset" round-trips.
	SetSkillMeta(ctx context.Context, arg SetSkillMetaParams) (AppSkill, error)
	// Mirror of the preview route's deadline on the version row (NULL = no active
	// preview); the draft-aware GC and the dashboard's "preview expired" state read
	// this without joining host_routes.
	SetVersionPreviewExpiry(ctx context.Context, arg SetVersionPreviewExpiryParams) error
	// Decrement the org's running storage total by the freed bytes (GC). GREATEST(0,…)
	// floors at zero so a reconciliation skew can never make the counter negative.
	SubOrgStorage(ctx context.Context, arg SubOrgStorageParams) error
	// The org's AI spend since a period start (the spend-cap check input and the
	// dashboard usage figure).
	SumAIUsageSince(ctx context.Context, arg SumAIUsageSinceParams) (float64, error)
	// Atomically claim a session for a turn: flip active/idle -> running and RETURN
	// the id ONLY if the claim won. A session already 'running' matches no row
	// (no-rows), so a concurrent second turn is rejected instead of racing on the
	// ai_messages (session_id, seq) unique key. The single-writer guarantee this
	// gives is what AppendAIMessage relies on.
	TryBeginAITurn(ctx context.Context, id string) (string, error)
	// Advance the custom-domain state machine (pending → verifying → verified/failed)
	// and the TLS status from a Cloudflare Status() poll.
	UpdateDomainStatus(ctx context.Context, arg UpdateDomainStatusParams) (AppDomain, error)
	// ===========================================================================
	// allowlist (Phase 2)
	// ===========================================================================
	// Add (or re-add) an email grant to a site's allowlist. is_external marks an
	// email whose domain is not an org verified domain; the external-sharing trigger
	// (0004) rejects is_external=true under a false org policy. Re-adding an email
	// resets it to a fresh pending (unclaimed) grant.
	UpsertAllowlistEntry(ctx context.Context, arg UpsertAllowlistEntryParams) (AppAllowlistEntry, error)
	// ===========================================================================
	// host_routes (Phase 2) — register/unregister a custom host in the global registry
	// ===========================================================================
	// Register a host → (org, site) in the GLOBAL registry. Used when a custom domain
	// verifies (the content host is the custom hostname). PK on host enforces global
	// uniqueness; a conflict with another org raises 23505 (ErrHostTaken). ON CONFLICT
	// updates only when the row is already owned by THIS (org, site) — a different
	// owner can never be overwritten because RLS makes its row invisible to UPDATE, so
	// the ON CONFLICT target row isn't visible and the upsert raises instead.
	UpsertHostRoute(ctx context.Context, arg UpsertHostRouteParams) error
	// Cast (or change) the caller's vote on a feed post (site or skill). One row per
	// (subject_type, subject_id, user); a flip from up to down overwrites value. RLS
	// scopes the write to the active org.
	UpsertPostVote(ctx context.Context, arg UpsertPostVoteParams) error
	// ===========================================================================
	// preview routes (AI builder / version previews) — time-limited draft hosts
	// ===========================================================================
	// Register (or renew) a preview host pinned to a specific draft version. PK on
	// host enforces global uniqueness like every other route; ON CONFLICT updates
	// only a row this org already owns AND that is a preview for the same site (a
	// canonical/custom route can never be silently downgraded to a preview).
	UpsertPreviewRoute(ctx context.Context, arg UpsertPreviewRouteParams) error
	// Insert or replace the per-site access policy (one row per site, PK = site_id).
	// password_hash is non-null only for mode='password'; expires_at / unlisted are
	// optional. The policy-mirror external-sharing trigger (0004) rejects mode='public'
	// under a false org policy.
	UpsertSiteAccessPolicy(ctx context.Context, arg UpsertSiteAccessPolicyParams) (AppSiteAccessPolicy, error)
	// Add a skill to a folder (or update its preset flag if already a member).
	UpsertSkillFolderItem(ctx context.Context, arg UpsertSkillFolderItemParams) error
	// Get-or-create a version by its (skill_id, content_hash): a no-op DO UPDATE so
	// RETURNING always yields the row whether it was just inserted or already
	// existed. Used by idempotent seeding so a retried seed can't raise 23505 and
	// abort the transaction. The no-op update sets status to itself.
	UpsertSkillVersion(ctx context.Context, arg UpsertSkillVersionParams) (AppSkillVersion, error)
	// NOTE: resolving a content host → owning site via the RLS-bypassing
	// app.resolve_host() SECURITY DEFINER function (migration 0006) is done with raw
	// pgx in the store (store.resolveHost), NOT sqlc: sqlc cannot infer column types
	// from a RETURNS TABLE function (it emits interface{}). The store scans the known
	// types directly. See services/api/internal/store/authz.go.
	// ===========================================================================
	// audit_log (Phase 4) — append-only record of sensitive actions
	// ===========================================================================
	// Append an audit row for a sensitive mutation. Runs inside the SAME RLS tenant
	// tx as the action it records (org-scoped by the per-tx GUC + the explicit org_id),
	// so an audit write can never land under the wrong tenant. actor_user is the verified
	// user id (null for a deploy-token actor); actor_token is the deploy-token id when a
	// token drove the action; metadata is freeform jsonb; ip/request_id/trace_id carry
	// the request provenance.
	WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) (AppAuditLog, error)
}

var _ Querier = (*Queries)(nil)
